### ISSUE TITLE
Change WHENCE constants?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/WASI#103]
It turns out that the `SEEK_CUR, SEEK_SET, SEEK_END` constants are pretty constant between native platforms - enough that in SDL (a very portable codebase), they are simply hardcoded. This caused breakage when I tried to [change emscripten's constants from musl's to wasi's](https://github.com/emscripten-core/emscripten/pull/9555#issuecomment-537100816), since `__WASI_WHENCE_CUR != SEEK_CUR` etc.

We can fix SDL and emscripten etc., but on the other hand, talking with @dschuff we thought maybe it's a good idea to make the wasi constants consistent with existing values. These are arbitrary values anyhow, and wasi is still unstable. This would cause some short-term inconvenience, but maximize compatibility with code in the long term.

Thoughts?

For comparison, errno codes definitely have differences between major platforms, and so there isn't a natural set of values to copy. (We [changed the codes in emscripten to match wasi](https://github.com/emscripten-core/emscripten/pull/9545), and that breaks our ABI but that's ok.)

**Comment by sunfishcode** [comment]
#106 landed, so this is fixed in ephemeral. We don't have a fixed schedule for when ephemeral updates to a versioned module, but I imagine we'll do so once we've batched up a few fixes.
