### ISSUE TITLE
Schedule a first meeting!

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/WASI#11]
Hello everyone, as a quick update, I'm working on setting up the first video-call meeting for the group, following the main CG process. It'll likely use zoom.us and follow the same overall format, at least to start with.

While the vote at last week's CG meeting was strongly in favor of launching this Subgroup, to do everything properly we need to officially select a chair and a charter, so we've now added agenda items to the next CG meeting [here](https://github.com/WebAssembly/meetings/blob/master/2019/CG-04-16.md#agenda-items).

In the meantime, please continue to [file issues](https://github.com/WebAssembly/WASI/issues) with questions, comments, and suggestions!

**Comment by sunfishcode** [comment]
Newly elected chair here :-). For the date and time of the first meeting, I expect we can start with once every two weeks, at one of the following times:
 - 16:00 UTC on Thursdays starting on May 2nd (same time as CG meeting, but on Thursday)
 - 17:00 UTC on Tuesdays starting on April 30 (immediately after the CG meeting)
 - 15:00 UTC on Tuesdays starting on April 30 (immediately before the CG meeting)

If anyone has a particular preference among these times, or a conflict, let me know, otherwise I'll pick one of the above and set up an announcement. As in the CG, I'll set up a calendar event with the video conference details, and people can contact me directly for an invite. Once we start having meetings, we can adjust the dates, times, frequency, etc., if needed.

I know the CG has discussed moving to different times; I expect this Subgroup will basically follow the CG.

While here, I want to remind anyone who hasn't participated in the WebAssembly CG before to [please join the W3C community group](https://www.w3.org/community/webassembly/participants), which is required for attending meetings or making substantive contributions.

**Comment by pchickey** [comment]
I would prefer to meet at 16:00 UTC or later

**Comment by rylev** [comment]
For those in Europe, earlier is better. Thanks 🇪🇺😀

**Comment by erights** [comment]
I have a repeating conflict every Tuesday at 15:00 and so would never be able to attend. (I really want to attend!)  Either of the other two are fine with me. Please do add me to any calendar entries. Thanks.

**Comment by erights** [comment]
Of the other two, I have  mild preference for Thursday 16:00. Thanks.

**Comment by sunfishcode** [comment]
Thursdays at 16:00 UTC, starting on May 2, seems to be the way to go! I'll set up a calendar event; contact me for an invite.

**Comment by sunfishcode** [comment]
As a quick reminder, the meeting is coming up in a week, so if you haven't contacted me for an invite and want to attend, or if you have reached out and I somehow missed you, please do so. Thanks!

**Comment by CryZe** [comment]
Hey, I'd like to attend the meeting.

**Comment by sunfishcode** [comment]
@CryZe Hello, please join [the WebAssembly Community Group](https://www.w3.org/community/webassembly/participants), and then contact me directly, such as via the email address in my github profile, and I'll send you an invite.

**Comment by rylev** [comment]
First meeting was held 🎉 You can find the notes for it in #35
