### ISSUE TITLE
Provide stardard test suite to make WASI implementation easy to test

### ISSUE THREAD

**Issue by gengjiawen** [WebAssembly/WASI#114]
Like https://github.com/tc39/test262

**Comment by devsnek** [comment]
feel free to use mine as a starting point. they're the lucet tests with some cleanup and additions: https://github.com/devsnek/node-wasi/tree/master/test/c

**Comment by AndrewScheidecker** [comment]
I think this is important, but is a dup of https://github.com/WebAssembly/WASI/issues/9.
