### ISSUE TITLE
about memory grow problem

### ISSUE THREAD

**Issue by GuoLei1990** [WebAssembly/WASI#119]
I have a memory problem!but I don't know create issues in which project. maybe is llvm or wasi. I use llvm and wasi-sdk compile wasm.
the problem is I init wasm lib version with code
`  var mem = new WebAssembly.Memory({ 'initial': initialMemory});
    fetch("laya.physics3D.wasm.wasm").then((response) => {
      response.arrayBuffer().then((buffer) => {
        WebAssembly.instantiate(buffer, {
          wasi_unstable: {
          },
          env: {
            memory: mem,
          }
        }).then((physics3D) => {
        });
      });
    });`
I compile the wasm with "--import-memory" by llvm ,but the initial memory not really work, wasm still grow the memory base the initial memory end.
for example I run a sample need 7M(or pages) wasm memory, if initial memory is 2M the memory in chrome is 2M+7M=9M，if the initialMemory is 100M the memory in chrome is 100M+7M=107M. in fact wasm ignore the initial memory and waste. so I must initial mininum size 2 pages with new WebAssembly.Memory({ 'initial': 2}); to avoid waste,but this is not I want. because this will grow memory many times,this is very slow,and especially when convert it to js version,it's very very slow,but i think the problem is in llvm or wasi. If I can sucess give a big memory to wasm, and wasm can use this memory first form start( not always grow from this memory end),will
save many performance,do not need to grow memoy many times,for my project(it's [a 3D engine](https://github.com/layabox/LayaAir)) the initial memory size must be a config write by developer according to their game, this is good for performance( avoid grow memory many times). before i use emsdk to compile wasm, don't have this problem. I hope this is my mistake cause!

**Comment by michaelvoronov** [comment]
Hi!

It is highly likely that the underlying problem is described [here](https://github.com/CraneStation/wasi-libc/issues/94#issuecomment-539045750). I will make PR with fix today or tomorrow.

P.S. Some more details in addition: WASI `dlmalloc` start by invoking [sys_alloc](https://github.com/CraneStation/wasi-libc/blob/master/dlmalloc/src/malloc.c#L4042). In the first call `sys_alloc` determines the memory base by invoking [sbrk(0)](https://github.com/CraneStation/wasi-libc/blob/master/dlmalloc/src/malloc.c#L4109). This call returns end of `initial` memory. So, memory between `__heap_end` and `initial` could be used by `dlmalloc` now.

**Comment by sbc100** [comment]
Is there a reason you need to `--import-memory`?   Currently WASI dictates that memory be exported.  At least for now.  I'm curious why you would need to import it?

**Comment by GuoLei1990** [comment]
@michaelvoronov  you are very good! I understand now,so WASI is designed like this now,and you will imporve and fix this problem tomorrow. Thank you very much,your fix  is very important for me.

**Comment by GuoLei1990** [comment]
@sbc100  Thank you for reply,the key reason is performance.
Environment:My Project is [a 3D Engine](https://github.com/layabox/LayaAir)

**Comment by GuoLei1990** [comment]
@sbc100  Thank you for reply,the key reason is performance.

Environment:My Project is a 3D game engine ,the source is javascript,but the physics module is wasm,the  developer use engine will adjust the physics initial memory by a config param to optimization performance(for example,A game need 16M at least,B  game need 32M).

Performance:so if initial memory can't work, wasm will grow the memory many times,I think this is slow,especially the js version(wasm2js tool convert) ,in chrome performance tool i can see this.before i use emsdk to compile wasm,emsdk support this and can avoid memory grow. now i use llvm+wasi,the file size and performance(Exclude memory grow problem) is good.

**Comment by sbc100** [comment]
OK that sounds like reasonable use case.  Perhaps we should open a separate issue to support imported memory, since WASI doesn't support that today.

**Comment by GuoLei1990** [comment]
@sbc100  Thank you very much! I hope you can support import memory👍，I will continuous attention this problem.

**Comment by tlively** [comment]
Would explicitly growing the memory to its configured size on startup be a simpler way to solve this problem? It sounds like the performance problem would be growing the memory many times, but surely growing it just once at the beginning would be ok.

**Comment by GuoLei1990** [comment]
@tlively    Yes! this is a flexible way to solve problems, I try [memory.grow API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/grow) before，but still can,t solve this problem. Do you know another API can work?

**Comment by tlively** [comment]
The only other way to grow the memory I know of is by the clang builtin function `__builtin_wasm_grow_memory`, but that should be identical to using the JS API. I suspect that the allocator doesn’t know how to use extra space that it does not request itself, but I don’t know for sure. Perhaps @sunfishcode knows whether this is expected to work.

**Comment by michaelvoronov** [comment]
@GuoLei1990 You could try https://github.com/CraneStation/wasi-libc/pull/114. 
About performance of importing memory - I am working mostly with standalone Wasm execution environments like wasmtime and wasmer and for them you could set initial memory pages in wasm binary for export memory. And then during instantiation they set initial position to value in the wasm file. I believe that browser should work exactly the same (e.g. v8 seems [so](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/wasm/module-instantiate.cc#L257)).

So, you could not use `--import-memory` and just set limits in wasm file - it seems that with this dlmalloc fix you will the behaviour you want.

P.S. To set limits you could convert wasm file to wat, write a correct x to the `(memory (;0;) x)` S-expression and then convert back to wasm.

**Comment by GuoLei1990** [comment]
@michaelvoronov [ its really work](https://github.com/CraneStation/wasi-libc/pull/114),Great!now the behaviour is what I want,the performance has improve now. Thank you and everyone relpy me,you are good people.

btw,what your means of "set limits in wasm file",you means lld port `--initial-memory`?

**Comment by michaelvoronov** [comment]
I meant that instead of using importing memory you could rather set memory limits in your compiled wasm file. According to the spec, each wasm file could define initial and maximum memory pages. So, you could set it by hands in your compiled file. E.g. by following way (with [wabt](github.com/WebAssembly/wabt/) installed) for `test.wasm` file:
1. Translate wasm to wat by `wasm2wat`:
```
wasm2wat test.wasm -o test.wat
```
2. Open with some text editor and find `(memory (;0;) x)`, where `x` - is a concrete number that depends on your program (note, that wat is just a special text Webassembly format). And `x` is also represent initial memory (in Wasm pages). You can replace it with your number (also you could set the maximum page count here).
3. Then translate wat to wasm back:
```
wat2wasm test.wat -o test_modified.wasm
```

**Comment by GuoLei1990** [comment]
@michaelvoronov  thank you very much! I understand.

**Comment by sunfishcode** [comment]
The original bug here seems to be fixed, in WASI libc, as noted [above](https://github.com/WebAssembly/WASI/issues/119#issuecomment-544264768). If there's anything further to discuss here, feel free to re-open this or file a new issue!
