### ISSUE TITLE
Publishing a snapshot

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/WASI#138]
We've had several PRs to the witx files, so it's time to start thinking about making an "unstable" snapshot, according to the [phases process](https://github.com/WebAssembly/WASI/blob/master/phases/README.md).

 - I've gotten feedback from a few folks that "unstable" is confusing. Should we rename "unstable" to "snapshot" while we have a chance here?
 - Are there any issues which are close to being resolved that we should wait for?

**Comment by cjihrig** [comment]
> I've gotten feedback from a few folks that "unstable" is confusing. Should we rename "unstable" to "snapshot" while we have a chance here?

Is "current" an option? It's already used in the phases document to describe the thing that transitions to "old."

**Comment by sunfishcode** [comment]
"snapshot" to me nicely conveys that these are versioned snapshots which are themselves stable, even as WASI evolves. "current" sounds like it might be the tree where the current work is happening, but that's what we call "ephemeral". But I'm happy to follow the sense of the Subgroup.

**Comment by sbc100** [comment]
snapshot sgtm.  I agree it conveys a little more meaning.

**Comment by MarkMcCaskey** [comment]
Snapshot sounds good to me too!

When we release a snapshot, it'd be very useful to have a changelog; here's my attempt at making one:

- #127 - change `__wasi_linkcount_t` to 64bits
- #125 - remove `clock.identifier` field in `subscription_t`
- 5d0b1e77f83d9ea9cac917ac61cfd9b26fa8b7de - reorder `whence_t`'s variants

And maybe #136 if it ships

The rest of the changes in [the](https://github.com/WebAssembly/WASI/commits/master/phases/ephemeral/witx/wasi_ephemeral_preview.witx) [history](https://github.com/WebAssembly/WASI/commits/master/phases/ephemeral/witx/typenames.witx) seem to be bug fixes that were applied to the current `unstable`, too.

**Comment by cjihrig** [comment]
Follow up question: once a new snapshot is created, what is the best way to know that a corresponding version of wasi-libc is available?

**Comment by sunfishcode** [comment]
Once we have a snapshot, we'll make the necessary changes to wasi-libc, and then wasi-libc will switch to the snapshot's module name, `wasi_unstable_preview0` or `wasi_snapshot_preview0` or whatever we call it, so that implementations know which ABI a given wasm module expects.

**Comment by sunfishcode** [comment]
Our story continues in #147.
