### ISSUE TITLE
is the doors opened to mobile app?

### ISSUE THREAD

**Issue by itacirgabral** [WebAssembly/WASI#15]
hi

I'm just had read lin's [article](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/). In the [scope](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-proposed-CG-subgroup-charter.md#scope) have input devices and  host's 'other resources'. And in the [future evolution](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-overview.md#future-evolution) have mentions:

> One possibility is that this API could evolve into something like Fuchsia's low-level APIs, which are more complex and abstract, though also more capable.

I would like some clarification of yours goals on mobile app development. Is a wasi ambitions can put webassembly apps into google and apple store?
Have any [web api](https://developer.mozilla.org/en-US/docs/Web/API) outside the wasi's use case?
Phonepag nor nativescript supports webassembly, but will be an natural fit to use wasi for all OS comunication in new framworks?

thanks!

**Comment by sunfishcode** [comment]
WASI intends to be a portable API suitable for a wide variety of environments, including mobile apps. 

However, WASI currently provides only very basic functionality. Typical mobile apps depend on a wide range of functionality for interacting with the UI, input devices, platform services, and many other things. Most of these are not covered by WASI yet. They're within the scope of the project though, so they may be covered in the future, if there are people willing to champion them.

**Comment by rylev** [comment]
Closing this as answer! 😀 If you have any more questions, don't hesitate to ask!

**Comment by timfayz** [comment]
Three years have passed. Any news for WASI (wasmtime) to be available on mobile platforms?

**Comment by jedisct1** [comment]
wasm3 works beautifully on mobile platforms, and includes WASI support.

**Comment by timfayz** [comment]
Oh! Thanks! I didn't know about that!
