### ISSUE TITLE
witx: consider using codespan crate for error highlighting 

### ISSUE THREAD

**Issue by pchickey** [WebAssembly/WASI#172]
I rolled my own error highlighting, but this appears to be nicer https://github.com/brendanzab/codespan

**Comment by pchickey** [comment]
Another candidate: https://github.com/rust-lang/annotate-snippets-rs

**Comment by linclark** [comment]
I'm closing this one (after checking with @pchickey) because the tools are under rapid evolution, so things will likely look different once that evolution slows down.
