### ISSUE TITLE
random bytes should not use char8

### ISSUE THREAD

**Issue by programmerjake** [WebAssembly/WASI#184]
https://github.com/WebAssembly/WASI/blob/01924c740b4d982310ce39d5881700fe0c75ad46/phases/ephemeral/witx/wasi_ephemeral_random.witx#L14-L25

`buf` should not have been changed to `char8` since it is random bytes -- not valid UTF-8

**Comment by sunfishcode** [comment]
Good catch! I've now submitted #198 with a fix.
