### ISSUE TITLE
Documentation inconsistency: markdown snapshot contains additional field in clock subscription

### ISSUE THREAD

**Issue by hberntsen** [WebAssembly/WASI#188]
The `identifier` field in the `__wasi_subscription_t` struct for the `poll_oneoff` function is documented in the [wasi_unstable_preview1.md](
https://github.com/WebAssembly/WASI/blame/8ff4e845d7baf48bf7cf7b6d9cc2a32a973da04e/phases/snapshot/docs/wasi_unstable_preview1.md#L2289) file, but not in the corresponding [`.witx` file](https://github.com/WebAssembly/WASI/blob/8ff4e845d7baf48bf7cf7b6d9cc2a32a973da04e/phases/snapshot/witx/typenames.witx#L555). I guess the markdown file has to be updated.

**Comment by kubkon** [comment]
Good catch! In fact, the `clock_id` field has now been renamed to simply `id` and the `identifier` field, as you aptly pointed out, has been dropped completely. I can submit a PR to rectify this, but I'm wondering how the docs are actually generated. @pchickey @sunfishcode do we generate docs manually from the corresponding `witx` files, or perhaps our `witx` tooling does most of it (if not all) for us? FWIW, I've seen the `docs` subcommand of `witx` utility but it seems to only generate a minimalistic markdown file.

**Comment by pchickey** [comment]
The `witx docs` subcommand does emit markdown containing everything in the `;;; doc comments` in the witx files. However, I did not take the time to tweak the output to look as nice as the existing md files, or do any checks to make sure that everything from the md files is consistent with the docs. Until that is done, we should still keep the md files up-to-date, but ideally we'd instead automatically generate them using `witx docs`.

I can't spend a ton of time working on that right now, so we'd need a volunteer to work on the doc generator to get it over the finish line. I'm happy to mentor that work if someone wants to take it on.

**Comment by kubkon** [comment]
@pchickey I reckon I could give auto-generated docs from witx files a go. When I have something working (minimal functionality yet correct ofc!), I'll open a PR and we can take it from there I guess. Let me know if that suits!

**Comment by pchickey** [comment]
Please do!
