### ISSUE TITLE
Provide a way to create sockets

### ISSUE THREAD

**Issue by rylev** [WebAssembly/WASI#20]
This is perhaps dependent on resolving #1 and #4, but a large gap in the wasi's capabilities is that there is currently no way to create sockets (i.e. no analogue to `accept` or `connect`). There are currently ways to read and write to sockets (`sock_send` and `sock_recv`), but without a good way to get a socket fd, these are not terribly useful.

Given that a major early use case for wasi is in the FaaS and "edge computing" space where networking is pretty important, it makes sense for filling out the socket API to be high on the priority list.

**Comment by npmccallum** [comment]
This is a requirement for us.

**Comment by maspe36** [comment]
Is there a working spec somewhere for this feature?

**Comment by sunfishcode** [comment]
The [wasi-sockets](https://github.com/WebAssembly/wasi-sockets/) API, which is now part of WASI, includes a way to create sockets.
