### ISSUE TITLE
WASI presence at 02/2020 in-person CG meeting?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/WASI#206]
The Wasm in person meeting is coming up:

https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md

Do we want to have subgroup breakout meeting?  Or perhaps a lunch / dinner meeting?   Lets use this ticket to propose agenda items.   Are there topics that could benefit from being discussed in person?

**Comment by sunfishcode** [comment]
We now have two presentations on the main agenda here:

https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md#agenda-items

For a breakout / lunch / dinner meeting topic, I propose: "Towards a WASI Embedded Profile". What should that mean? What functionality should it include? What functionality should be optional?

Thoughts?

**Comment by sunfishcode** [comment]
At the CG meeting, we had [two WASI presentations](https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md), one on a WASI embedding API, and one on WASI's security model and its relationship to various in-flight wasm proposals.
