### ISSUE TITLE
WASI modules for executing eBPF

### ISSUE THREAD

**Issue by kubkon** [WebAssembly/WASI#218]
I’m definitely not an expert in Linux kernel programming or eBPF for that matter, but from what I saw at FOSDEM2020, it seems that WASI modules could be a fit for running eBPF extensions in the kernel (provided we could embed WASI runtime in the kernel, etc.). It might be a crazy idea and not at all viable, but I thought I’m gonna mention it here and gather some feedback.

**Comment by devsnek** [comment]
a runtime could provide intrinsic functions that are compiled to ebnf instructions, and you could import those alongside wasi, but I don't think it's a good target for wasi itself since it's so platform specific.

**Comment by kubkon** [comment]
Ah, that makes sense. Thanks for chipping in and clarifying!

**Comment by sbc100** [comment]
Agreed.  Evaluating the wasm binary format for this purpose might make sense, but the WASI API is really user-space focused.

**Comment by szihai** [comment]
Ebpf does have a user space hook for users to inject code. So wasi can call ebpf interfaces to handle network and file related tasks.

**Comment by sunfishcode** [comment]
We now have some feedback here! Moving forward, there are a lot of technical possibilities in this space, so I think the next step here would be for someone to file a new issue articulating a specific use case or problem to be solved.
