### ISSUE TITLE
Proposal:  rename $ciovec and $iovec

### ISSUE THREAD

**Issue by igrep** [WebAssembly/WASI#247]
When I saw the name "ciovec" for the first time, I couldn't find what the prefix `c` stood for. As long as I look up, there are no other names by such a convention.

So how about renaming `$ciovec` and `$iovec` into names which sound their usage more clearly (e.g. `$iovec_read` and `$iovec_write`).

~~Or, just specifying `iovs` of `read` as `$out`, and `iovs` of `write` as `$in` might be an option.~~
Sorry I misunderstood that `$in` and `$out` were keywords.

**Comment by sunfishcode** [comment]
For background, `iovec` comes [from POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/writev.html), and `ciovec` comes [from cloudabi](https://github.com/NuxiNL/cloudabi/blob/master/cloudabi.txt#L964). I don't yet have a strong opinion on whether the advantages of renaming `iovec` in particular are worth deviating from POSIX here. Anyone have opinions on this?

One thing we could very easily do is actually mention the purpose of `ciovec` in its documentation comment in typenames.witx. And yes, changing the name of the arguments from `iovs` would be easy too.

Another thing we could consider here would be to add non-vectored versions of `read` and `write`, which would eliminate the hassle of setting up `iovec` arrays in simple cases. There's an argument that adding these are just special cases of the vectored functions, and this would make the API less minimal in a sense, however it seems like a judgement call we could make.

**Comment by igrep** [comment]
I personally prefer `$iovec_read` and `$iovec_write`, as shown in the description.
We can see their roles just at a glance.
But I'm also curious about other ideas

**Comment by igrep** [comment]
> Another thing we could consider here would be to add non-vectored versions of read and write, which would eliminate the hassle of setting up iovec arrays in simple cases. There's an argument that adding these are just special cases of the vectored functions, and this would make the API less minimal in a sense, however it seems like a judgement call we could make.

From that point of view, I agree to that idea if defining such specialized functions helps the WASM modules be smaller as the runtimes provide the specialized functions.
IMO WASI doesn't have to be minimalistic.

(But I think we should discuss that further in a separate issue... 😕 )

**Comment by caspervonb** [comment]
Is there a reason why these two are distinct types beyond "in the future" we might X? As far as I remember they have the same fields.

> Another thing we could consider here would be to add non-vectored versions of read and write, which would eliminate the hassle of setting up iovec arrays in simple cases. **There's an argument that adding these are just special cases of the vectored functions**, and this would make the API less minimal in a sense, however it seems like a judgement call we could make.

I'd make that argument, it's effectively a trivial overload that can be done as a simple two liner inline function in user-land.

**Comment by sbc100** [comment]
@caspervonb, I having trouble seeing what you are advocating for.    Are you agreeing with the argument that these are simple special cases and therefor *not* worth adding?

**Comment by sbc100** [comment]
@sunfishcode what about simply removing the vectored I/O functions?  Are there real world application that rely on these for performance or correctness reasons?  I can't say that I've seen them used much in real code.   I guess maybe something like leveldb mabye?

**Comment by igrep** [comment]
@caspervonb 

> Is there a reason why these two are distinct types beyond "in the future" we might X? As far as I remember they have the same fields.

You mean we don't have to have the two separate types `iovec` and `ciovec`?
`ciovec` is different from `iovec` in mutability: `ciovec` is read-only.
I think that is a good separation to clarify the intention that `write` doesn't modify the argument.

**Comment by caspervonb** [comment]
Ah there's a const pointer in ciovec, in that case `ciovec` kinda makes sense (even tho it's by accident) to read as "const input output vector".

**Comment by kubkon** [comment]
Would renaming `fd::read` to something like `fd::readv` or `fd::read_vectored` help?

**Comment by igrep** [comment]
@kubkon Interesting. But that's a different problem.
The point here is that "What the prefix c stood for is not clear" (at least for people who see the name for the first time).
More concretely, when I saw the signature of `write`, I suspected `ciovec` was a typo for `iovec` until reading the definition of `ciovec`.

**Comment by kubkon** [comment]
Gotcha! I'm happy with going with something more readable here. After all, WASI doesn't have to carry over the same cryptic nomenclature that was invented for POSIX/CloudABI. I'm somewhat biased by Rust in general, but perhaps we could go with something similar to what we have in Rust's libstd? Namely, [`IoSlice`] and [`IoSliceMut`]?

[`IoSlice`]: https://doc.rust-lang.org/std/io/struct.IoSlice.html
[`IoSliceMut`]: https://doc.rust-lang.org/std/io/struct.IoSliceMut.html

I'd personally prefer to go with a name pointing more at mutability than `iovec_read` vs `iovec_write`. If `Mut` is not acceptable/undesirable, perhaps `Const` or similar? `iovec` and `const_iovec`? In a way, `ciovec` was meant to signify `const` `iovec`.

**Comment by igrep** [comment]
`iovec_mut` and `iovec` sounds excellent! Or `iovec_mut` and `iovec_const` are also good.

> In a way, ciovec was meant to signify const iovec.

Yeah, it took me some minutes to realize that for the first time. 😓

**Comment by caspervonb** [comment]
> @caspervonb, I having trouble seeing what you are advocating for. Are you agreeing with the argument that these are simple special cases and therefor not worth adding?

Yes @sbc100, I'm agreeing that they are very simple special cases not worth adding as they're just adding noise to the interface.

**Comment by linclark** [comment]
This API is very likely to change once the interface types proposal is further along. Since making a change like this will take a good bit of coordination, it's likely not worth the churn in the meantime. We'll address this as part of a larger discussion once there's more clarity around IT.
