### ISSUE TITLE
Hardware abstractions module for embedded devices 

### ISSUE THREAD

**Issue by olanod** [WebAssembly/WASI#251]
Another WASI module request to further discuss :)
Having worked a bit with the rust [embedded HAL](https://github.com/rust-embedded/embedded-hal) I find it great to have this common interface layer to to write against without worrying much about the the hardware the code will be running on, this initiative is making Rust very attractive for embedded development and dare I say, one day be more popular than C.  
One step beyond I see is the portability of WASI, imagine writing not only in Rust but C or any other language code that is deployed to a wide variety of hardware. In a different issue there was a guy already showing the wasm3 interpreter running on an ESP32! give it some APIs to access the GPIOs and the Bluetooth stack and :boom:  

I think looking at the abstractions created by the embedded-hal project and defining a WASI equivalent is a must have for the embedded market WASI will surely be targeting.

**Comment by sunfishcode** [comment]
This is a cool idea! If anyone is interested in writing up witx descriptions of these APIs, that'd be a great place to start. Feel free to ask questions and/or post incomplete sketches here, and ask for help!

**Comment by linclark** [comment]
I'm going to close this one out since it's not actionable at the moment. But if someone wants to start work on a proposal in this direction, do feel free to post an issue or PR and we'd be happy to work with you on developing it.

**Comment by rahul-thakoor** [comment]
Hello!

I am very new to the wasm/wasi ecosystem, but I'm interested in learning some more and help with such an implementation if possible. 

Context:
I have a similar use case where I could like to be able to access GPIO pins or even i2c and SPI based devices from a wasm module. I think using the existing wasi filesystem api I can achieve something like this to some extent. E.g I can implement the linux sysfs-gpio interface partially but then the wasm module is not portable per se - it would only run on linux host for instance.

I am trying to understand how to make such a platform-agnostic API such that the same module works on Linux, Windows, macOS, or even microcontroller hosts as long as there is a runtime that implements the hardware abstraction api.

Not sure if this is the right place for such a discussion. Feel free to redirect accordingly 😃 

Thanks :+1:
