### ISSUE TITLE
What are the requiremements on modules?

### ISSUE THREAD

**Issue by nomeata** [WebAssembly/WASI#258]
Starting from this repo’s README or https://wasi.dev/ I have a hard time finding what precisely is the WASI spec , and what is additional information. Based on https://wasi.dev/ I would look at https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-documents.md but it’s unclear where to go from there. Likely https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md, but that seems to be incomplete; it only gives the API, but I miss information on
 * what is the entry point to the module? `(start)`? An export called `_start`? Is it optional or required?
 * what about the memory that the system API access? Does it need to be exported/imported etc?

Essentially the question of “what makes a Wasm module a program that runs on WASI” is missing here. Is that written somewhere but not linked well, or is it not even written down?

**Comment by sbc100** [comment]
I think you want: https://github.com/WebAssembly/WASI/blob/master/design/application-abi.md

**Comment by nomeata** [comment]
A bit sparse (e.g., are these exports required), but yes :-)
Could this be linked from https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-documents.md?

**Comment by sunfishcode** [comment]
I've now opened https://github.com/bytecodealliance/wasmtime/pull/1562 to create the link!

And, the wording in that page has recently been revised; does that address your comment about sparseness? Or if there are other ways we could improve that page, please let us know!

**Comment by nomeata** [comment]
Yes, I think it addresses most of my questions, namely that
 *  exporting `_start` or `_initialize` is mandatory, even if your program only serves the purpose of heating up your CPU in `(start)`,
 * but that the `memory` export is optional, and only required if you actually use any of the WASI API

I wonder if it would make sense to specify what happens when you do not export a memory – does the module not even load, or does does it load provided it does not import and WASI functions, or does it it load and the WASI functions trap upon use?

Not that these questions are hugely important in the context of WASI; but I am looking here for design guidance when designing similar interfaces.

**Comment by sbc100** [comment]
I agree it would be good to specify all those things, and encode those rules in a test suite.

**Comment by pchickey** [comment]
I created this tool to validate modules against a witx spec. It has a few more deps than I'm eager to add to the `witx` tool, but I could be convinced to add it if people wanted to use it https://github.com/bytecodealliance/lucet/tree/master/lucet-validate
