### ISSUE TITLE
Running a WASI program as a web worker with stdio as messages?

### ISSUE THREAD

**Issue by coolreader18** [WebAssembly/WASI#259]
At first, it seems like it'd be natural to map WASI processes and stdio to the browser with [wasmer/wasi](https://github.com/wasmerio/wasmer-js/tree/master/packages/wasi) and workers and postMessage passing, but I can't seem to get it to work in practice due to the need for `fd_read` to be synchronous, and the fact web workers can't block (e.g. with `while (true) {}`) while waiting for a message to be sent, since control can't be yielded to the event loop. Does anybody have any ideas for implementing something like this, or is this basically impossible? (without widespread `SharedArrayBuffer` support)

**Comment by caspervonb** [comment]
Continuations, which aren't a thing right now but I think @rossberg is working on a proposal for stack switching as I remember a talk about it but can't find the link video right now.

Until then, you can use a transform like @kripken's asyncify to wind/unwind and rewind the stack.

**Comment by kripken** [comment]
[Asyncify](https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html) is definitely meant for this, as @caspervonb said. It's designed to run on any wasm file. You would need support on the JS side too, though (not sure if wasmer-js that was mentioned has that; in emscripten there is [a PR](https://github.com/emscripten-core/emscripten/pull/9151)).

**Comment by coolreader18** [comment]
Great, thank you! I'll look into asyncify; it seems like I would need to fork wasmer-js/wasi.

**Comment by caspervonb** [comment]
Stumbled across the talk I was referring to earlier: [Evolving WASM into a proper misnomer](https://www.youtube.com/watch?v=pq-Pa2Fj4nE), stack switching is at around [55 minutes in](https://youtu.be/pq-Pa2Fj4nE?t=3245).

**Comment by sunfishcode** [comment]
The question here seems answered; please reopen or file new issues if there's any followup!
