### ISSUE TITLE
Consider giving the current snapshot a number

### ISSUE THREAD

**Issue by jendrikw** [WebAssembly/WASI#261]
At the time of writing, the current version is snapshot_1. It would be great it one could link to it in a way that doesn't change in the future, like https://github.com/WebAssembly/WASI/tree/master/phases/snapshot1.

**Comment by sunfishcode** [comment]
Good idea! We're in the process of reorganizing things right now as it is, so we should do this too while we're here.

**Comment by sunfishcode** [comment]
I did a quick test to see how Github handled symlinks, and in the Web interface it appears to present them as plain files which contain the target string. Does anyone know of a way to achieve the effect of having versioned directories, while also having a stable URL to point to the latest snapshot?

If there isn't a better way to do this, we could probably get away without having the stable URl, and just have a README which we manually update.

**Comment by pchickey** [comment]
I think we should have a manually updated README link which we maintain for now. I wouldn't want to invent any sort of symlink scheme now since we are planning to re-organize things in the near future.

**Comment by linclark** [comment]
This will happen as part of #360, so I'm going to close this one out.
