### ISSUE TITLE
Struct sizes of event and subscription

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/WASI#266]
We've recently run into problems regarding the layout or more precisely sizes of the `event` and `subscription` structs, and I'd like to have some clarification on the following aspects:

* According to [the relevant paragraphs in docs.md](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md#-event-struct), the `event` struct will always contain the `event_fd_readwrite` struct as by extension, so an `event` struct is always exactly 32 bytes, regardless of event type.

* According to [the relevant paragraphs in docs.md](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md#-subscription_u-union), the `subscription` struct will always reserve the size necessary to store the largest variant of the `subscription_u` union, so a `subscription` struct is always exactly 48 bytes, regardless of subscription type.

* The size of a `prestat` is always exactly 8 bytes in 32-bit, and 16 bytes in 64-bit.

Are these assumptions correct? If not, could you point me into the right direction? If correct, do you think it'd be useful to add the sizes to the documentation, so other language implementers trying to model these where there's no native concept of C structs don't run into similar problems in the future?

**Comment by pchickey** [comment]
Hi, thanks for this bug report. The `witx` tool exposes the layout information of datatypes programmatically, and we're sure that the calculated layout matches the C ABI by generating assertions in C and Rust code, but we never actually surface this information in the generated docs.

I just discussed this issue with @torch2424 and he's going to add the layout information to the docs generator soon.

In the meantime, the header generator in wasi-libc puts the calculated size, align, and offsets into this file: https://github.com/WebAssembly/wasi-libc/blob/master/libc-bottom-half/headers/public/wasi/api.h
