### ISSUE TITLE
Broken link in DesignPrinciples.md

### ISSUE THREAD

**Issue by igrep** [WebAssembly/WASI#269]
From https://github.com/WebAssembly/WASI/commit/694e08560945c579af138032b77da1b865a1605b#diff-80a9f10dab0824be1a2060988fb5a687R246-R247

The referred page is 404.

> `[linking
proposal](https://github.com/WebAssembly/interface-types/blob/linking/proposals/interface-types/linking/Explainer.md)`

What happened to the linking proposal of the interface types?
I couldn't find the branch `linking` and any files that looks related to it in master.

**Comment by sunfishcode** [comment]
The linking proposal has evolved and migrated here: https://github.com/WebAssembly/module-types/pull/3.

**Comment by sunfishcode** [comment]
This was fixed in #278!
