### ISSUE TITLE
Incorrect size returned by __wasi_environ_sizes_get

### ISSUE THREAD

**Issue by shritesh** [WebAssembly/WASI#27]
The documentation for `__wasi_environ_get` says "The sizes of the buffers should match that returned by `__wasi_environ_sizes_get`" but the WASI implementations that I tested (wasmtime and wasmer) expect a buffer with space for additional null pointer at the end. [The sysroot too implements it that way.](https://github.com/CraneStation/wasi-sysroot/blob/fad009dc1d6c8d5b0deb9a2cb894c04be1dc9098/libc-bottom-half/crt/crt1.c#L54)

This is in contrast with `__wasi_args_get` and `__wasi_args_sizes_get` that say the same thing but do as documented.

I'm not sure if this is a bug or the expected behavior. If it is, it should be documented as such.

**Comment by sbc100** [comment]
The C arrays exposed to user code for `environ` and `argv` are are both defined to be NULL terminated. 

I agree it is currently unclear weather the NULL termination is the responsibility of  the __wasi_environ_get/__wasi_args_get syscalls, or of the calling code (i.e. the code in crt1.c).

**Comment by devsnek** [comment]
recently tripped me up as well while implementing this

**Comment by peterhuene** [comment]
Based on [@sunfishcode's earlier comment](https://github.com/CraneStation/wasi-libc/pull/72#issuecomment-497366587), I think it's best to not force WASI into a convention that might be viewed as an implementation detail for a libc implementation.

I've put up #128 so we can discuss this further.
