### ISSUE TITLE
Lower case names for proposal repos

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/WASI#273]
The proposed scheme is:

            1. https://github.com/WebAssembly/WASI-http-proxy/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-classic-command/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-poll/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-handle-index/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-clocks/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-random/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-filesystem/tree/master/phases/ephemeral/witx
            1. https://github.com/WebAssembly/WASI-streams/tree/master/phases/ephemeral/witx

What do we think about keeping the `wasi` part in lowercase?   Its easier to type an fits better with the lowercaseness of the rest of the repo name.   Also it makes `WASI-http-proxy` a little less weird, no?

We already have repos like `wasi-libc` and `wasi-sdk` so in terms to existing repo names the lowercase is already more common..

**Comment by sbc100** [comment]
Plus.. typing all those uppercase letters make my pinky tired.

**Comment by caspervonb** [comment]
Was thinking the same thing when I saw the agenda commit but did not want to be *that guy*.

**Comment by sunfishcode** [comment]
Works for me. I've now renamed all the proposal repos to be lowercase.
