### ISSUE TITLE
How to interact with the filesystem of WASI?

### ISSUE THREAD

**Issue by leoleoasd** [WebAssembly/WASI#279]
Having compiler in WASM and compiling c code to WASM is a great solution to replace cloud-based ides under situations where performance is not required. Compiling the compiler, for example, clang itself, to WASM seems easy as described in the WASM SDK (though I haven't tried yet), but how to make the compiler running in the browser use the SYSROOT and input file?

In general, how to interact with the filesystem of a program running under WASI?

**Comment by sbc100** [comment]
For an exampe of how this might work in the browser take look at : https://github.com/binji/wasm-clang?files=1

And the accosiated talk: https://www.youtube.com/watch?v=5N4b-rU-OAA

**Comment by leoleoasd** [comment]
> For an exampe of how this might work in the browser take look at : https://github.com/binji/wasm-clang?files=1
> 
> And the associated talk: https://www.youtube.com/watch?v=5N4b-rU-OAA

This is an awsome solution, thanked a lot.
