### ISSUE TITLE
WASI API considerations

### ISSUE THREAD

**Issue by dumblob** [WebAssembly/WASI#28]
@sunfishcode @hinzundcode

This is just to continue discussion from https://github.com/CraneStation/wasmtime/issues/91 .

Apart from Drawbridge etc. we shall take into account also the surrounding environment of the "near future" (actually already current) at Microsoft. See [Universal Windows Platform](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide ) APIs and the environment to get a grasp of it. Put emphasis especially on the last chapter [How the Universal Windows Platform relates to Windows Runtime APIs](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#how-the-universal-windows-platform-relates-to-windows-runtime-apis ) leading e.g. to [CoreApplication Class](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplication ).

**Comment by sunfishcode** [comment]
People interested in helping digest this content and extracting actionable ideas and concepts are invited to re-open this issue or file new issues!
