### ISSUE TITLE
[Proposal] Extend wasi to be able to communicate with the embedder

### ISSUE THREAD

**Issue by jakeblaxon** [WebAssembly/WASI#280]
I’m interested in building an orchestrator within webassembly. The goal is to be able to provide a service similar to docker-compose, where I can simulate having two or more wasm modules connected over a dns network or to the same file system, for example, while running other modules in their own isolated environments at the same time.

I believe this can be accomplished with a custom implementation of wasi, that’s tailored to the user’s specifications. The wasi implementation would keep track of environment information for the various modules that invoke it. For example, if a module requests access to a file A, the implementation behind the wasi call can check which “virtualized environment” that module is running in and connect it to the same file _A on the host system as the other modules running in that same environment. If another module requests access to the file A, however, and it’s not part of that environment, the wasi implementation would connect it to a different file _B on the host system that’s considered file A in this separate and isolated environment.

This custom wasi implementation could be written in wasm itself, using the default wasi implementation provided by the embedder as a foundation, which would allow for maximum portability. However, in order to ensure that the orchestrated modules themselves are provided this implementation (instead of the default wasi implementation), each embedder would have to be configured manually wherever we want these modules to run. To avoid this, we could have an “orchestrator” wasm module that itself invokes the modules from within it and provides the custom wasi implementation. However, this would require that this orchestrator module have the ability to communicate with the embedder and be able to invoke new wasm modules while specifying the providers for that specific invocation. The embedder allows the user to do this on the host system, but not via any wasi interface that I currently know of.

With this line of reasoning, I would like to propose a new set of wasi commands that allow you to interact directly with the embedder. These commands would provide the same abilities that are usually given by the embedder to the user on the host system, such as dynamically invoking new wasm modules from a file, while specifying permissions and providers for that module. 

Making these commands available would essentially allow us to create arbitrarily nested wasm environments (like nested vm’s) without sacrificing performance, since each module would still be run natively by the embedder (instead of through a wasm vm written in wasm, for example). The nested environments would be managed by the nested orchestrators that are wasm modules themselves. This would allow us to solve the classical problem of vm’s, where we sacrifice performance for isolation as we nest vm’s within vm’s.

So far I’m not aware of any effort on this front, which is why I’m opening this issue to track it. However, if there’s already an issue dedicated to extending wasi to be able to communicate with the embedder, please let me know. I’m curious to hear others’ thoughts on this, and what possible next steps are. Looking forward to the discussion. Thank you!

**Comment by sbc100** [comment]
I think there are plans to enable this kind of thing (often refereed to a virtualization or interposition):  see https://github.com/WebAssembly/WASI/blob/master/docs/DesignPrinciples.md#interposition.

Exactly how programs and loaded and linked is still TBD.  There is work over in the module-types proposal that will probably be somewhat relevant:  https://github.com/WebAssembly/module-types/pull/3

Note: I would avoid calling this "communicate with the embedder" since that seems like it could apply to all WASI APIs.

**Comment by jakeblaxon** [comment]
This is exactly what I was looking for. Thank you!
