### ISSUE TITLE
Versioning of interfaces (modules)

### ISSUE THREAD

**Issue by axic** [WebAssembly/WASI#29]
I'm working on [Ewasm](https://github.com/ewasm) which tries to bring WebAssembly to Ethereum. We are evaluating how we could use WASI (core) or other modules.

As part of the design process we have realised that versioning is an important feature to have: https://github.com/ewasm/design/issues/121

I wonder how WASI plans to solve versioning of its interfaces. I see some potential options:
- Would it be similar to #12 having a function to query the version?
- A system similar to glibc where either the namespace or the name has a pre/postfix? (This is option a) in the linked issue).
- A custom section listing interface version (This is option b) in the linked issue).
- Adding versioning to the wasm import sections themselves.

Probably there are other/better proposals. Was there any previous discussion about this topic?

**Comment by sbc100** [comment]
IIUC this is what is being discussed in #2.   Or am I missing something?

**Comment by sunfishcode** [comment]
WASI now has versioning of interfaces, using a version number formatted within the module-name field of wasm imports. And the mechanism for querying interfaces is [optional imports](https://github.com/WebAssembly/WASI/blob/master/design/optional-imports.md).
