### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by pchickey** [WebAssembly/WASI#290]
The WASI subgroup is changing the default branch names in all repositories to `main`.

Please consider this a tracking issue. It is not intended for public debate.

* [x] Change branch name
* [ ] Update CI
* [ ] Update build scripts
* [ ] Update documentation

**Comment by sbc100** [comment]
I think `trunk` fits better with the tree/branch analogy, but I don't feel super strongly.

**Comment by findgriffin** [comment]
In addition to `main` and `trunk` there are other options like `canon`, `mainline`, or `root`.

**Comment by tlively** [comment]
My reading of this issue (and please correct me if I'm wrong) is that this was a closed-door, unilateral decision. I would like to think that the CG is able to discuss this sensitive issue in an understanding and productive manner, so I'm disappointed with the lack of transparency and engagement here.

For what it's worth, I think `main` is a good name, but I know many people have many different personal naming preferences. My hope is that we can skip the bikeshedding and all agree to use `main` for now if we also agree that we will later adopt any new standard name GitHub and the upstream git project settle on. Also, we should adapt any new standard for all the WebAssembly repos, not just for WASI. Does that sound like a reasonable plan?

**Comment by sunfishcode** [comment]
@tlively I apologize for the unclear communication here.

At present, git branch names are within the discretion of WebAssembly repo maintainers for the repos they maintain. Git branch names don't contribute to the official output of the standards process, and if they don't use exclusionary language, they don't have a significant impact on anyone's ability to participate. @pchickey offered to help with the rename, and I agreed that it makes sense to do.

And I agree -- `main` seems to have emerged as the leading alternative, going by a quick scan of news articles, so it makes sense to go with `main` for now, but if a different name emerges from Github, the WebAssembly organization as a whole, or other relevant entity, we should switch to it, even if it means we end up with the mild inconvenience of having to change the name twice.

**Comment by pchickey** [comment]
One issue that came to light when I investigated renaming is we currently publish specs (witx files and markdown documents) that are accessible underneath the URL `repo/blob/{branchname}/`. While renaming the branch is important, I would like to do it without disrupting links on web pages, and tooling that fetch witx specs from those URLs. Ideally, GitHub will release official support for renaming branches in the near future (Nat has said so on twitter without detailing what or when) which will include redirecting requests to the renamed branch.

So, I propose we hold off on renaming until either July 1, or we get some communication from GitHub on how branch renaming could be officially supported.

**Comment by sunfishcode** [comment]
Github has [made some changes](https://github.com/github/renaming), including picking `main` as the new default name. Seamless renaming of existing repositories isn't ready yet, but Github says [it will be supported later this year](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-), so I think we should wait until that's ready, and then use it to do the rename.

**Comment by pchickey** [comment]
I confirmed with the GitHub engineering manager that
> Blob url redirects will indeed be covered in the next milestone slated to ship by EOY.

**Comment by pchickey** [comment]
The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
Latest commit
```

**Comment by caspervonb** [comment]
So does this break scripts or is github doing some kind of redirecting when you checkout the master branch?

**Comment by sbc100** [comment]
IIUC it does break any script that hardcodes 'master'.   Its kind of shame there is no automatic-mirroring thing we can setup for some transition period.   We just tried this this tradition on binaryen and decided to delay until we can figure out all the possible failure modes that folks will hit.

**Comment by pchickey** [comment]
My understanding matches sbc's. Fortunately there are redirects in place for http pages (not including http git access) - we waited for that, specifically, so that if anyone was fetching witx from the `github.com/WebAssembly/WASI/blob/master/...` it would continue to work.
