### ISSUE TITLE
Congratulations on merging WASI into Deno!

### ISSUE THREAD

**Issue by EdSchouten** [WebAssembly/WASI#294]
I just saw [this article on Hacker News](https://news.ycombinator.com/item?id=23729256) that WASI has been merged into Deno. That's great news! Congratulations to all of you!

Back in 2015, I started working on CloudABI, hoping that I'd be able to make a lasting change to how people build software and think about security. Unfortunately, the project never got as much traction as I had hoped. It was simply too ambitious for me to maintain on my own. This is why I abandoned the project in 2017-2018. In the meantime, I have moved on to other things, most notably work in the area of distributed build systems/clusters ([Bazel](https://bazel.build), [Buildbarn](https://github.com/buildbarn)).

Seeing that you folks have been able to distill the good pieces, turn it into something that works well, and create a large momentum behind it brings joy to my heart. I wish you all the best in the future!

Ed

**Comment by devsnek** [comment]
wasi has also been supported in wasmtime, lucet, node.js, wavm, and probably more.

**Comment by caspervonb** [comment]
Thanks for your work on CloudABI @EdSchouten 😄

**Comment by pchickey** [comment]
Thank you for showing us the way, @EdSchouten !

**Comment by sunfishcode** [comment]
Indeed, thanks @EdSchouten! WASI has benefited immensely from CloudABI's thoughtful design.
