### ISSUE TITLE
Scheduling of in-person meeting during June CG meeting

### ISSUE THREAD

**Issue by bitwalker** [WebAssembly/WASI#30]
As discussed at the end of the subgroup meeting today, we want to schedule an official adjunct meeting during the June CG meeting in A Coruña, Spain.

While an informal meeting was discussed amongst some members out-of-band, @sunfishcode indicated that an official meeting should occur during the CG meeting times, to avoid excluding those whose travel plans are already set in stone. However we still need to determine scheduling, which times are available for the subgroup to meet, and what, if any, conflicts may prevent some folks from attending.

It may be useful to discuss potential agenda topics here, but I'll defer to @sunfishcode and others who may wish to use the current PR process for agendas to manage that discussion.

**Comment by littledan** [comment]
We can probably find space in the office for such a discussion, but it may be hard to get another space with as good of an A/V setup as the main room. Just let me know what you need. If you want to have this meeting the day before or after, or at some odd time of day, just let me know and I'll see if we can work out the space; it seems unfortunate if attendees have to choose which track to go to.

**Comment by binji** [comment]
We're doing some meeting coordination here: https://github.com/WebAssembly/meetings/issues/398. Though we have yet to schedule times for each topic. I'll try to get a rough schedule worked out soon.

**Comment by tschneidereit** [comment]
Closing this as the June meeting has happened.
