### ISSUE TITLE
Import resolution in WASI

### ISSUE THREAD

**Issue by PoignardAzur** [WebAssembly/WASI#32]
Importing a wasm module directly from another wasm module [is currently mostly impossible](https://stackoverflow.com/a/55797858/3511753). Using wasm modules together essentially requires it to be done from JS code.

This is slated to change with the [esm integration proposal](https://github.com/WebAssembly/esm-integration/tree/master/proposals/esm-integration) in the works.

That proposal is web-centered, though. Since WASI is positioned as the non-browser standard platform, it should define its relationship with the esm proposal. I'm also interested in how WASI positions itself with regards to [WICG's import maps](https://github.com/WICG/import-maps).

Speaking personally, I'm a big fan of npm's dependency tree model as a way to avoid dependency hell (although it can [bring subtle problems](https://www.reddit.com/r/haskell/comments/4zc6y3/why_doesnt_cabal_use_a_model_like_that_of_npm/?ref=share&ref_source=link)). In the long run, I want to be able to use a wasm package manager to install a program/library, have the PM install all the dependencies and sub-dependencies in their own directory tree, and never have to worry about incompatible package versions and the like; and be able to just type `rm -rf wasm_modules` or something similar and be assured that every trace on earth of my dependencies have been erased.

Also, while I'm doing armchair design, I think having a subset of import maps could be pretty useful for serverless computing and the like, to provide easy-to-shim modules as capabilities without having to write your own WASI interpreter:

```
import api : "@cloudflare.workers";

func main() {
    api.startTask(...);
    // ...
}
```

In the above pseudocode example, the import statement would compile to an import instruction, which would point to a shim in a test environment, and to a library provided by cloudflare in production.

Thoughts?

**Comment by dumblob** [comment]
>Speaking personally, I'm a big fan of npm's dependency tree model as a way to avoid dependency hell (although it can bring subtle problems). In the long run, I want to be able to use a wasm package manager to install a program/library, have the PM install all the dependencies and sub-dependencies in their own directory tree, and never have to worry about incompatible package versions and the like; and be able to just type `rm -rf wasm_modules` or something similar and be assured that every trace on earth of my dependencies have been erased.

Well, I definitely agree, that WASI needs some 'import resolution' mechanism, but I would argue, that `npm` has a viable mechanism. I would strongly recommend everyone to listen carefully to Russ Cox in his talk about [package management with emphasis on versioning and dependency resolution](https://www.youtube.com/watch?v=F8nrpe0XWRg ) before continuing discussion in this thread just to avoid possibly premature conclusions or ideas (because it's too easy to go astray in this case as some of the conclusions in the talk are **not so intuitive** as one would expect).

**Comment by PoignardAzur** [comment]
I'm a little confused. You're implying that you disagree with me, but it sounds like you're arguing for a npm-like dependency model, which is also what I'm arguing for, so... did I misunderstand something?

Either way, the video looks interesting.

**Comment by dumblob** [comment]
>but it sounds like you're arguing for a npm-like dependency model, which is also what I'm arguing for, so...

Basically it boils down to the subtle differences between `npm`'s and `Russ Cox`'s dependency management as they are of high importance with severe impact. That's why I wouldn't use `npm` as an example, but rather the `Russ Cox`'s talk.

**Comment by sbc100** [comment]
I think it is useful to distinguish between what WASI is aiming to provide (access to a consistent set of system APIs) and a more general wasm packaging system that is capable of composing wasm modules.  My feeling is that WASI should not be aiming to fill the role of package manager.   I think this will help us keep WASI simple and targeted.

Assuming we can agree on this  perhaps it would be useful to list explicit non-goals for WASI such as:
- providing a framework for dynamic linking of wasm modules
- providing an npm-like packaging system for wasm modules.

(BTW I also found Russ Cox's talk very informative).

**Comment by PoignardAzur** [comment]
I guess I could always write an "Import name standardization" proposal with different specifications for web and WASI embeddings.

That said, I that some minimum rules for import names should be a prerequisite for WASI, given that it will rely on importing a specific module's name. For instance, we might want a rule that says that any built-in module name take the form `$foobar` to help analysis tools, eg `$wasi_fs` or `$nodejs/http`, in which case WASI would have to conform to that rule.

**Comment by titzer** [comment]
One consideration here is restricting the syntax of names for imports. In the JS space, we made essentially no restrictions on the syntax of names, and this makes it impossible to add additional metadata to an import (e.g. an encoding of additional type information), which would be useful for things like WebIDL bindings. Therefore I think it makes sense to reserve some encoding freedom in names for potential metadata in the future.

**Comment by PoignardAzur** [comment]
And... done: https://github.com/WebAssembly/design/issues/1286

@sunfishcode I would appreciate your feedback on this; in particular, if the syntax gains traction, would you consider renaming `wasi_unstable` to `@wasi` or `@wasi_unstable`?

**Comment by sunfishcode** [comment]
@PoignardAzur I haven't thought deeply about actually using WICG import maps or the specific syntax yet, but the overall idea looks good. And yes, the name `wasi_unstable` is just meant to be a placeholder until we have an actual plan :-).
