### ISSUE TITLE
Confused about implementing storing to/loading from caller's mem in WASI

### ISSUE THREAD

**Issue by osa1** [WebAssembly/WASI#327]
[WASI functions][1] typically get pointer arguments for various kinds of buffers. A [store][2] or load instruction in Wasm uses the memory of the *current function's module*, not the caller's module. That means that if we follow a similar idea when implementing WASI functions we won't be able to fill the buffers passed by the caller, because the WASI module and the caller will have different memories.

I guess in principle it would be possible for the caller module and WASI to share the memory via imports, but if I compile a WASI program I don't see it importing a `mem` from the WASI module.

I also think that the WASI module could not import the caller's `mem` as there may be multiple modules that use WASI in a single runtime environment.

WASI could be implemented in a special way at the host level to use the caller's module when getting the memory to use. My question is basically whether that's how it's supposed to implement or not.

It seems hacky to me that from the outside WASI looks like an ordinary Wasm module, but if I pass a memory address to a function of it, even though I don't import its mem (and I think it cannot import the my module's mem), it's somehow able to modify mem of my module.

Am I missing anything or is this really how WASI is supposed to be implemented?

[1]: https://github.com/WebAssembly/wasi-libc/blob/master/libc-bottom-half/headers/public/wasi/api.h
[2]: https://webassembly.github.io/spec/core/exec/instructions.html#t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-store-xref-syntax-instructions-syntax-memarg-mathit-memarg-and-t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-store-n-xref-syntax-instructions-syntax-memarg-mathit-memarg

**Comment by nomeata** [comment]
https://github.com/WebAssembly/WASI/issues/258 might be relevant: WASI programs _export_ their memory (it looks like you only looked for imports), so the WASI module can access it.

Also see https://github.com/WebAssembly/WASI/blob/master/design/application-abi.md

> Regardless of the kind, all modules accessing WASI APIs also export a linear memory with the name `memory`. Data pointers in WASI API calls are relative to this memory's index space.

**Comment by osa1** [comment]
@nomeata thanks, that quote explains it.

It seems hacky still, but I guess we have to live with it for now.
