### ISSUE TITLE
Why are pointers `i32`?

### ISSUE THREAD

**Issue by yagehu** [WebAssembly/WASI#332]
Why do we use `i32` as pointers? Doesn't `u32` make more sense since it can't be negative?

Sorry if this is a dumb question. I have a weak background in systems.

**Comment by lachlansneff** [comment]
Wasm doesn't have a `u32` type. The `i32` type just represents 32 bits of data, it isn't assumed to be any particular form.

**Comment by yagehu** [comment]
Wow I'm a dumbass :100: I blame rust :p
