### ISSUE TITLE
Where are concepts like `struct` and `enum` defined?

### ISSUE THREAD

**Issue by yagehu** [WebAssembly/WASI#336]
In the snapshot typenames witx, there are definition like `struct` and `enum`. I can infer what they mean and how to work with them. But are they formally defined anywhere?

For example, iovec is a struct:

```wat
;;; A region of memory for scatter/gather reads.
(typename $iovec
  (struct
    ;;; The address of the buffer to be filled.
    (field $buf (@witx pointer u8))
    ;;; The length of the buffer to be filled.
    (field $buf_len $size)
  )
)
```

**Comment by sunfishcode** [comment]
No, they're not formally defined. The best we have at the moment is [the witx tooling code](https://github.com/WebAssembly/WASI/tree/master/tools/witx).

Witx is based on the `wit` in [module linking](https://github.com/WebAssembly/module-linking/), and adds some anticipated features from other proposals, especially [interface types](https://github.com/WebAssembly/interface-types). When the syntax for interface types is defined, we expect to modify witx to adopt it. Eventually, most (perhaps all) of `witx`'s unique features should be available in plain `wit`.

**Comment by yagehu** [comment]
Thanks. Answered my question.
