### ISSUE TITLE
Quick Question: possible to compile Bash to target WASI?

### ISSUE THREAD

**Issue by mallochine** [WebAssembly/WASI#340]
EOM

this is more like a quick help question but I don't know which channel to put my question.

**Comment by sunfishcode** [comment]
WASI currently lacks include the ability to launch and control child processes, and the ability to control a virtual terminal including escape sequences and `SIGHUP`.

**Comment by mallochine** [comment]
Is it technically possible, given enough time and the right expertise, to implement the launch/control child processes using Web Workers

**Comment by sunfishcode** [comment]
Yes, see [Browsix](https://browsix.org/), for example. That's not built on WASI, but it does show that you can basically do what's needed to run Unix-style shells in browsers.
