### ISSUE TITLE
Is there a minimum required resolution for clocks?

### ISSUE THREAD

**Issue by caspervonb** [WebAssembly/WASI#341]
Clocks can have up to nanosecond precision but is there a minimum required precision for a conforming implementation?

**Comment by sunfishcode** [comment]
No, even a "broken clock" implementation which always returns the same time would be conforming. Ideally `clock_res_get` should accurately describe the level of precision provided, though that's also not strictly guaranteed.

If you need these kinds of guarantees, it's something that could be explored. The first step would be to investigate applications that need it -- do they need real-time guarantees, or just guarantees about the relationship between `clock_time_get`'s clocks and other specific time sources?

**Comment by caspervonb** [comment]
> No, even a "broken clock" implementation which always returns the same time would be conforming

Hm, even for the monotonic clock? 🤔 

> If you need these kinds of guarantees

Primarily just a thought for wasi-test, had to relax resolution a bit to make Deno and Node pass reliably and that got me wondering if we're just doing bare minimum what POSIX does or being more specific about it.

**Comment by programmerjake** [comment]
> > No, even a "broken clock" implementation which always returns the same time would be conforming
> 
> Hm, even for the monotonic clock? 🤔

the monotonic just guarantees it'll never go backwards. not going forwards is a valid implementation IIRC.

**Comment by caspervonb** [comment]
> the monotonic just guarantees it'll never go backwards. not going forwards is a valid implementation IIRC.

Alright, thanks for the insight!
