### ISSUE TITLE
Is WASI support any UI api?

### ISSUE THREAD

**Issue by yylittlefish** [WebAssembly/WASI#346]
Hi,
There're many webassembly runtime to support WASI, like wasmtime, wasmer and WAVM. 
WASI covers POSIX fileds including network, filesystem, clock, randam number, etc.
It seems WASI not include any UI api, right?
and I wonder if there're any wasm runtime support UI api?

**Comment by sbc100** [comment]
No, there are no UI or graphics APIs in WASI today.

There are some plans afoot for a low level framebuffer api and also a GPU API:

- https://github.com/WebAssembly/WASI/issues/174
- https://github.com/WebAssembly/WASI/issues/53
