### ISSUE TITLE
witx: What is `supertypes` in `HandleDatatype`?

### ISSUE THREAD

**Issue by yagehu** [WebAssembly/WASI#357]
[`HandleDatatype`](https://github.com/WebAssembly/WASI/blob/52cb4fea61b20cf87e15653e0e3df28fe8b432e6/tools/witx/src/ast.rs#L298-L300) is defined as:

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct HandleDatatype {
    pub supertypes: Vec<TypeRef>,
}
```

What is `supertypes`? The only use of `handle` in snapshot preview is:

```
(typename $fd (handle))
```

**Comment by pchickey** [comment]
At one point I had the poor idea to allow handles to be a subtyping hierarchy but fortunately we do not actually use this feature anywhere. It turns out this isnt compatible with using wasm extern refs as handles. Ignore the field, and I will remove it from the language when I get a chance.

**Comment by yagehu** [comment]
Thanks. Answered my question.
