### ISSUE TITLE
Standardize capability passing

### ISSUE THREAD

**Issue by badeend** [WebAssembly/WASI#369]
As a Wasm+WASI host I want to provide my sandboxed Wasm modules a secure way to open files when and how they see fit. In other words, I would like to pass my modules the ability of opening a file, not a preopened file itself. As far as I can see, WASI currently does not have a standardized interface for this use case. Is there any interest in adding this kind of interface to WASI? 

I've created a quick example function signature based on `path_open`:
```
file_open(capability_token: externref, oflags: oflags, fs_rights_base: rights, fs_rights_inheriting: rights, fdflags: fdflags) -> (errno, fd)
```

I have mentioned files only, but the same could also apply to directories and sockets.

**Comment by devsnek** [comment]
is this just describing the reification of TOCTOU?

**Comment by badeend** [comment]
I had to look up the term [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use), but I presume you're referring to a scenario like this:

1. The host performs some checks. Only if they pass, the host issues a `capability_token` (from my example above) and communicates it with the child module.
2. Something in the world changes which invalidates the checks performed in step 1.
3. The child module calls `file_open(capability_token, ...)`. The host, knowing that it has received a valid `capability_token`, does not recheck and blindly executes the request.

In that case: yes, that would be a race condition. Depending on whatever these hypothetical check are, the problem might be solved by moving the checks to step 3.

Even though `capability_token`s could be used for custom permission checks, that's not what I had in mind. The way I see it is that, from the consumer's point of view, `capability_token`s are simply an opaque replacement for absolute paths and only gives the holder the capability to call file_open. It does not bring any guarantees about whether the call will fail or succeed.

"capability_token" could be renamed to something like "opaque path" to better reflect the intent.

**Comment by devsnek** [comment]
Thanks for clarifying. I think the usage many of us have been envisioning is a bit unix-like in that the paths themselves form your api. For example instead of `open(get_x_path())`, your system might be more like `open("/x")`.

**Comment by badeend** [comment]
That makes sense.

But, and forgive me if I have misunderstood either you or the current WASI spec: 
I wonder how much of the "paths-as-apis" vision can remain in heavily sandboxed environments where absolute paths don't exist. Because you always need access to a directory file descriptor to base your path on. In case there's a workaround for that: in order to use the path/"api": `/dev/null`, the Wasm module would need access to the root folder, which doesn't seem like a good idea. An alternative would be for the host to emulate a root filesystem with only a `dev` folder with in it a single `null` file and maybe some other files deemed "safe" by the host.
Anyways,.. I'm not here to undermine the UNIX philosophy :)

Putting my initial proposal aside. What my issue boils down to, I guess:

WASI currently provides no straightforward way to pass unopened files and/or directories to modules without also giving access to the entire parent directory. Consequences of only passing preopened files include:
- the passed file/directory must already exist.
- wasm modules can't specify the open() flags.
- wasm modules can't open and close files multiple times.
- wasm modules can't delete the file/directory. (but they *can* truncate the entire file, which most end-user would probably consider one and the same)

From a sandboxing point of view I can think of three options:
- Accept the limitations
- Grant access to the parent directory (not really sandboxing anymore)
- Create complicated constructs emulating a directory containing only the file in question.

**Comment by badeend** [comment]
FWIW: a similar problem seems to be acknowledged in the "Berkeley socket rules" section here:
https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-capabilities.md#berkeley-socket-rules
