### ISSUE TITLE
Move all WASI modules to separate repositories

### ISSUE THREAD

**Issue by linclark** [WebAssembly/WASI#382]
The ideal end goal of WASI modularization is for each of the modules contained in this repo to have its own repo.

Once we have the syntax in place for depending on types from other directories (#378), we need to move the witx files for the different modules to their own repositories.

**Comment by sunfishcode** [comment]
We have now migrated all the proposals to their own repos, such as [wasi-filesystem](https://github.com/WebAssembly/wasi-filesystem) and [wasi-sockets](https://github.com/WebAssembly/wasi-sockets).
