### ISSUE TITLE
Does WASI considerate memory64?

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/WASI#400]
After https://github.com/WebAssembly/memory64 applied,
we will have memory address of 64bit,
How the WASI handling 64bit pointers properly?

Specifically `Pointer<u8>`

**Comment by devsnek** [comment]
I recently did a review of WASI for memory64 and didn't find any issues. A compliant implementation should work fine.

**Comment by sunfishcode** [comment]
I'm not aware of anyone running WASI on wasm64 yet, so likely there will be some work in the tools, however all the tools are built with wasm64 in mind, so in theory it should be straightforward. The `Pointer` type would be lowered to `i64` on wasm64.

If you have further questions, please re-open or file new issues!
