### ISSUE TITLE
document endianness

### ISSUE THREAD

**Issue by vapier** [WebAssembly/WASI#449]
i get that WASI is built on top of WASM and thus it can be easy to "just know" that WASI is obviously little endian, but for the sake of clarity, it might help to explicitly state this in the API docs.  especially when one considers that there have been cases of interopt using a specific endian all the time (e.g. "network byte order" is always big endian).

**Comment by sunfishcode** [comment]
Is there a particular place or particular functions where it would be helpful to document this? WASI follows the endianness conventions that all little-endian platforms follow, so it's not immediately clear where we should document this.

Also, it's worth noting that interface types are endian-independent, so as WASI transitions to those, the API specifications will be endian-independent, and any endianness sensitivity will be a result of a specific binding layer.

**Comment by vapier** [comment]
who do you see as the target audience of the WASI spec ?  is it application programmers (i.e. people writing "hello world"), or language bindings implementers, or runtime implementers ?

if application programmers need to read this spec, then we have failed them.  they should never need to peek under the hood here.  the only thing they need is a POSIX compiler & environment.  which is what wasi-sdk does now fairly well.

people working on language bindings & runtimes very much need to know these details.  no level of abstraction at the API level changes that.  the whole point of WASI is to connect completely unrelated runtimes and still have things Just Work.  we're never going to get away from raw memory access (like we have with pointers now) which means these details need to be defined precisely.

if we do somehow manage to make details like endianness irrelevant years in the future, it's pretty trivial to just delete such sections & discussions from the spec.  but i don't see how that aspiration is relevant now.  the WASI API is steeped up to its eyes in multibyte integers with no explanation as to its encoding, and it's doing a disservice leaving things ambiguous.  i still don't see why you think it's reasonable that everyone should naturally assume everything is little endian.  there is nothing in the spec to suggest that.  assuming host cpu endianness seems like a more reasonable default assumption.

**Comment by sbc100** [comment]
I tend to agree that we should not avoid documenting how things work today (as in `wasi_snapshot_preview1`) because we have aspirations to side step certain issues in the future.   

We do, after all, document the requirement to export the wasm memory, even though we hope to avoid that one day too.

**Comment by linclark** [comment]
> I tend to agree that we should not avoid documenting how things work today (as in wasi_snapshot_preview1) because we have aspirations to side step certain issues in the future.

We're very close to making the switch to using Interface Types based on Canonical ABI, as Alex has demonstrated in recent meetings.

With that, it feels like endianness should be documented at the Canonical ABI level, rather than in WASI itself. That could happen in the Interface Types repo as soon as https://github.com/WebAssembly/interface-types/pull/132 lands

**Comment by sunfishcode** [comment]
The endianness of the Canonical ABI is [now](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#loading) [documented](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#storing) as "little".

As seen in these links, the ABI documentation is already greatly improved for Preview2. In addition to endianness, it has full ABI documentation. Preview1's documentation isn't anywhere near this complete, and wouldn't be enough for someone to build an implementation on, even if we added endianness. So at this point, I think it makes sense to focus on Preview2 as the direction of the platform going forward.
