### ISSUE TITLE
Make release process more modular

### ISSUE THREAD

**Issue by linclark** [WebAssembly/WASI#450]
As discussed in the June 17 meeting (with an update on October 21), we have been working to make it easier to propose WASI APIs. This includes the previously discussed work on a more ergonomic syntax for defining APIs, a proposal template, and a simplified repo structure, which are all close to completion.

In addition to those changes, we need to look at the release process. The plan for WASI has evolved since its inception, but the way we thought of the release process didn’t change to reflect that.

## Problems with the current release process

WASI is a much more modular set of APIs than are traditionally part of a system interface. But our process is to group all of these APIs into a single “snapshot” for release.

This causes the following problems.

1. A snapshot has a single integer release number. With all proposal updates being grouped under this single version, there’s no sensible way to use semantic versioning to communicate about API changes. 
1. Most hosts will only support a subset of APIs, yet we bundle all the APIs into a single file. This means that consumers need to add a processing step to remove unnecessary APIs.
1. The snapshots are in the main WASI repo, even though the work happens across different repos. Creating a single artifact in the WASI repo creates confusion about where issues should be filed.

## Proposed new release process

Let’s look at another possible way of doing things. Instead of releasing a monolithic snapshot and versioning that snapshot, each API would cut its own releases. 

These releases would still go through the WASI standardization process, which means that we would vote before major and minor releases. These releases would then be listed in an additional column in Proposals.md.

This release process would maintain the rigor of the standardization process, but would do so in a way that reflects the modularity of the APIs and addresses the issues above by:

1. Making it possible for APIs to follow semantic versioning
1. Allowing hosts to easily specify exactly which APIs that they want to support before feeding them through tooling
1. Providing a single source of truth (the proposal repo) for all APIs

I will be bringing this proposal up for discussion in the October 21 meeting, and if no major concerns come up during the conversation, plan to propose a vote for the subsequent meeting.

**Comment by syrusakbary** [comment]
> Regarding semantic versioning in particular, there was quite a lot of discussion around this early on I think we decided it didn't make sense to use this. 

Here's the previous discussion: #360
