### ISSUE TITLE
Library on demand (LOD) in WASI

### ISSUE THREAD

**Issue by vasuskimo** [WebAssembly/WASI#455]
LOD, library-on-demand is a cross between a library and a service using Web Assembly WASI. LOD obviates the need for linking during compile time. Simply call LOD, like a web service when you need and it will be downloaded from some repo and when you are done simply release it. 

There is a precedence in Javascript/node where one can do this kind of dynamic import.

This LOD feature would become an imperative as WASI begins to gain traction.

**Comment by devsnek** [comment]
isn't this just dynamic linking?

**Comment by vasuskimo** [comment]
> isn't this just dynamic linking?

Well, I meant dynamic linking in the true sense. Could you do "import("https://foo.bar")  or i="include("https://foo.bar") and not from Javascript.

**Comment by sbc100** [comment]
WASI itself doesn't really deal with how your program and its libraries are composed.   Perhaps that module linking proposal is better place to discuss this kind of thing? : https://github.com/WebAssembly/module-linking

**Comment by vasuskimo** [comment]
Created an issue in https://github.com/WebAssembly/module-linking as @sbc100  pointed out and closing this issue.
