### ISSUE TITLE
when wasm64-wasi will be supported?

### ISSUE THREAD

**Issue by renxuqiang** [WebAssembly/WASI#456]
is there any working process on this? thanks

**Comment by aardappel** [comment]
@alexcrichton

**Comment by alexcrichton** [comment]
AFAIK no one is working on this, but it is pretty unlikely to be supported as-is out-of-the-box with projects like wasi-libc today. I'm also not personally aware of any WASI implementations that support memory64 at this time. 

To answer the original question of when will it be supported, to the best of my knowledge the answer is unknown.
