### ISSUE TITLE
Do we need a new term for a WASI "module"?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/WASI#46]
We've been talking about WASI APIs being provided by WASI "module"s.    But a WebAssembly modules built against WASI APIs might also logically be called a WASI modules.

Since WASI APIs are not (in general) provided by WebAssembly modules but by the embedder directly i think it might make more sense to come up with a better term for a WASI API.

Ideas?   

- WASI API?
- WASI sys-module?
- WASI component?

**Comment by xtuc** [comment]
- WASI support
- WASI environment
- WASI platform
- WASI host

**Comment by sbc100** [comment]
Alternatively we can continue to use WASI module to refer to the system components and come up with a new name for a program that uses WASI?

**Comment by binji** [comment]
* interface
* WAD
* WAM
* WAI
* WASAPI

**Comment by skyne98** [comment]
WASI Extensions? The same route as RISC-V and Vulkan?

**Comment by sbc100** [comment]
I was asking about the core APIs.  Right now we seem to be calling them "modules" but that seems confusing.

**Comment by cjihrig** [comment]
I like the idea of calling them the WASI API.

**Comment by sunfishcode** [comment]
I've taken to using the term "API module" when there's a need to disambiguate, and it seems to work well.

**Comment by sbc100** [comment]
I think the original premise of this issue no longer holds: "Since WASI APIs are not provided by WebAssembly modules but by the embedder directly...".     These days my understanding is that folks are very excited about virtualization and really want this statement to be false.

So perhaps this whole issue can just be closed?

**Comment by sunfishcode** [comment]
Good point :-).
