### ISSUE TITLE
What if allow to create a socket in WASI?

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/WASI#462]
I am going to ask about a fundamental problem of *socket APIs* like *who is going to create a socket and pass it to a .wasm module in a standalone runtime?* 

Let's say there are two programs in language C, a TCP server and a TCP client. Both use POSIX socket APIs(like `socket()`, `bind()`, `accept()`, `listen()`, and so on). The goal is to translate both into WASM modules and to run in a standalone runtime.

According to the design limitation of [cloudabi](https://github.com/NuxiNL/cloudlibc#introducing-nuxi-cloudabi), I learned that there should be someone to create the socket resource outside the WASM world and pass it to WASM modules. (I guess this is the reason there are only `recv()` and `send()` in WASI). 

Does it mean the compiling tool (from C to WASM) should generate an additional *glue* code to work with the WASM module lately? Otherwise, I think another way is to ask authors of programs to split their code into several parts.

**Comment by badeend** [comment]
To those who are interested; I've created a draft proposal at: https://github.com/badeend/WASI-Networking

**Comment by KernelErr** [comment]
Hi, I took a skim on `draft.md`. The `accept` method does not require a `fdflags` argument. However, this document (https://github.com/WebAssembly/WASI/blob/0ba0c5e2e37625ca5a6d3e4255a998dfaa3efc52/phases/snapshot/docs.md#-sock_acceptfd-fd-flags-fdflags---resultfd-errno) seems to have that flag for specifying non-block mode. @badeend

**Comment by sunfishcode** [comment]
Fulll sockets is now being developed, in the [wasi-sockets](https://github.com/WebAssembly/wasi-sockets) repository.
