### ISSUE TITLE
path_open anchor is re-used between the flag and the function

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/WASI#469]
path_open anchor points to the function:

https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#path_open

This makes the following text easy to be confused:

> [fd_datasync](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#fd_datasync): bool The right to invoke fd_datasync. If [path_open](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#path_open) is set, includes the right to invoke [path_open](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#path_open) with [fdflags::dsync](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#fdflags.dsync).
https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#record-members

Because when you click on the link that's implied as a flag, it goes to the function. Unless you scroll around to find that fd_open is also a right, or look closely at the word "invoked" and infer the mistake, brain breaks a bit.

Correcting the anchors somehow or prefixing right flags with "flag_" or "right_" can sort this out

**Comment by sunfishcode** [comment]
Yes, the whole "rights" system in WASI is derived from CloudABI, and the consensus from both users and implementors is overwhelmingly that it's complex, confusing, and not worth it to continue supporting. I've removed it from the latest [wasi-filesystem](https://github.com/WebAssembly/wasi-filesystem/blob/main/wasi-filesystem.wit.md).

**Comment by codefromthecrypt** [comment]
good advice. thanks. I wish there was a place to know the "minimum viable API" for snapshot1, though, as there are code using it and would prefer not to burn time on cul-de-sacs.. any ideas?

**Comment by codefromthecrypt** [comment]
Thanks tons, and appreciate the candor! I'll close this one for now as targeted issues are better.
