### ISSUE TITLE
Cut off sentence in Contributing.md

### ISSUE THREAD

**Issue by badeend** [WebAssembly/WASI#472]
@linclark What should the end of this sentence be? :) 

> As part of moving to the next phase, the champions need to define the acceptance criteria for Phase 4. This is because WASI includes APIs that cover a diversity of different domains and use cases, so the .

**Comment by linclark** [comment]
Ha, whoops! 😬 Thanks for the catch, @badeend!

It should be  "so the acceptance criteria can be very different between different proposals." I'll make that fix now.
