### ISSUE TITLE
Use memory handles?

### ISSUE THREAD

**Issue by SoniEx2** [WebAssembly/WASI#476]
Last time we looked at it, WASI seemed to do a weird thing where it exports functions and imports memory, but the memory must be exported by the module that imports the functions...

Which is extremely confusing, can be impossible in some wasm VM designs, and kinda defeats being capability-based tbh.

There should be some sort of "memory handle" that gets passed to WASI whenever it needs access to a memory object.

Drawback: neither reference types nor multi-memory enable memory handles. So this would need a new wasm proposal.

**Comment by sunfishcode** [comment]
The details aren't all completed yet, but we're expecting the interface-types proposal to provide facilities for passing data through buffers, in a way that completely avoids the need for memory to be exported and imported.

**Comment by sunfishcode** [comment]
If you wish to propose a first-class memory-handle type, please do so at the WebAssembly CG level, since that would be a language feature rather than a WASI API.
