### ISSUE TITLE
A command World proposal

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/WASI#509]
We should create a CLI command World proposal.

As has been discussed at various WASI Subgroup meetings, the idea is to have a `command` entrypoint function which has arguments for things like command-line arguments, environment variables, preopens, and stdio, and to have it include wasi-filesystem, wasi-sockets, wasi-clocks, wasi-random, and others that make up a typical CLI command environment.

**Comment by sunfishcode** [comment]
(I originally opened this in wasi-filesystem by mistake; I've now transferred it to the WASI repo.)

**Comment by codefromthecrypt** [comment]
what does "World proposal" imply? this is a top-level proposal like wasi-filesystem? would it be called wasi-command?Besides what has been mentioned, would this be the thing that defines in fact memory is required for everything? or would each proposal (e.g. filesystem) have in their WIT that the guest needs to export that?

**Comment by sunfishcode** [comment]
Wit defines a [World](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#item-world) construct, which is a way to collect sets of interfaces. For additional background I also have a [blog post about Worlds](https://blog.sunfishcode.online/what-is-a-world/).

This command World would be the first WASI proposal that contains a World rather than just being an interface. We'll likely need to do some administrative work to set this up, including updating to a newer version of the wit tooling to support this.

The spec that defines how linear memory used in wit APIs is the [Canonical ABI](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md).

**Comment by sunfishcode** [comment]
This proposal should specify the meaning of the first argument, to fix https://github.com/WebAssembly/wasi-classic-command/issues/7, which is also being fixed for preview1 in https://github.com/WebAssembly/WASI/pull/510.

**Comment by sunfishcode** [comment]
Her'es a rough sketch of what the world might look like:
```wit
default world wasi-command {
  import wasi-clocks: pkg.wasi-clocks
  import wasi-default-clocks: pkg.wasi-clocks.wasi-default-clocks
  import wasi-stderr: pkg.wasi-stderr
  import wasi-filesystem: pkg.wasi-filesystem
  import wasi-random: pkg.wasi-random
  import wasi-poll: pkg.wasi-poll
  import wasi-io: pkg.wasi-io
  import wasi-sockets: pkg.wasi-sockets
  import wasi-exit: pkg.wasi-exit

  variant preopen {
     file(descriptor),
     directory(descriptor),
     socket(socket)
  }

  export command: func(
    stdin: input-stream,
    stdout: output-stream,
    args: list<string>,
    env-vars: list<tuple<string, string>>,
    preopens: list<tuple<preopen, string>>
  ) -> result
}
```

**Comment by sunfishcode** [comment]
The command world proposal is now in active development at https://github.com/WebAssembly/wasi-cli !
