### ISSUE TITLE
failed to parse export section, effective type size too large

### ISSUE THREAD

**Issue by Finfalter** [WebAssembly/WASI#518]
A custom generator generates functions (in Rust) in order to put them in a WASI module. All functions must be visible from the outside and, thus, shall be exported. In order to do so, the Rust code is accompanied by a corresponding .wit file. The code is built by 
```bash
cargo wasi build --release
```

**Given the number of exported functions exceeds a certain threshold (~20,000), I get the following error:**
```
error: failed to process wasm at ../my_module.rustc.wasm

Caused by:
    failed to parse export section

Caused by:
    effective type size too large (at offset 911791)`
```
Is there a limit for _**type size**_? 
What is the limit? 
Can I increase it?

**Comment by pchickey** [comment]
This issue is specific to an implementation and belongs in bytecodealliance/wasm-tools, can you please refile it there?

**Comment by Finfalter** [comment]
I did. Thank you very much for your feedback!
