### ISSUE TITLE
[idea] Utilize WASI to further native web app integration

### ISSUE THREAD

**Issue by kellytk** [WebAssembly/WASI#52]
Something that prevents a web app from appearing as native is that it's an 'app within an app' and doesn't appear in OS-level app switchers.

A web app should be able to express its intent to be used natively and if the user permits, the OS would begin presenting it in its app switcher and other task management tooling separate from its hosting browser.  Naturally this would require some form of cooperation between web devs, web standards, browsers, and OSs.

How should those pieces look and fit together, and what could WASI do, if anything, to contribute?

**Comment by devsnek** [comment]
most browsers already have an option to show tabs as separate windows/tasks (depending on the context of the os).

I'm not sure how wasi would factor into this, but my initial impression is that it doesn't.

**Comment by cjihrig** [comment]
The request sounds more like a PWA than something WASI related. I agree with @devsnek's assessment.
