### ISSUE TITLE
Remove wasi-grpc from Stage 1 proposals

### ISSUE THREAD

**Issue by aschrijver** [WebAssembly/WASI#540]
I was just made aware in https://github.com/WebAssembly/wasi-grpc/issues/1 that there are no plans for `wasi-grpc` yet. But finding it in the Stage 1 list which then leads to an empty (template text only) repo is quite confusing.

Imho entry should either be removed from [Proposals.md](https://github.com/WebAssembly/WASI/blob/main/Proposals.md), or instead a reference added to the `wasi-grpc` README linking to the issue https://github.com/WebAssembly/WASI/issues/520 where it was placed out of scope.

**Comment by Mossaka** [comment]
I think this makes sense as currently there is no plans or interests for designing `wasi-grpc`. I can add a reference to this issue in the `wasi-grpc` README.

**Comment by Mossaka** [comment]
Just updated the `wasi-grpc` README
