### ISSUE TITLE
wasn't signal removed from wasi?

### ISSUE THREAD

**Issue by trcrsired** [WebAssembly/WASI#565]

**Comment by pchickey** [comment]
Its hard to understand your question without more context, but yes, there are some functions related to signal handling present in WASI preview 1 for which no sensible implementation was possible. They were removed from the WITX spec after that preview was released (https://github.com/WebAssembly/WASI/pull/136), but no further releases of the WITX spec were made.

Signals are not part of any of the Preview 2 proposals and we don't expect they will be part of WASI in the foreseeable future.
