### ISSUE TITLE
Proposal: Add process info

### ISSUE THREAD

**Issue by vdshb** [WebAssembly/WASI#567]
This is a proposal to make process info available as a standard WASI API. 

I am, at the moment, primarily looking for WASI equivalent of nodejs' [process.platform](https://nodejs.org/api/process.html#processplatform) and [process.arch](https://nodejs.org/api/process.html#processarch), but I believe it will be useful to add other info like [process.pid](https://nodejs.org/api/process.html#processpid) and [process.env](https://nodejs.org/api/process.html#processenv) (Probably already available. I'm new to WASI and use it through kotlin-wasi interface, so not sure about details).

**Comment by abrown** [comment]
I believe the environment is already available as a part of wasi-cli (see [here](https://github.com/WebAssembly/wasi-cli/blob/main/command.md#functions-16)). I'm not sure what value PID would be in a WebAssembly instance (they're not _really_ processes) but there is a way to emulate this in wasi-libc, e.g., by just returning `42` every time. For the platform and arch values, are you looking for something like `wasi` and `wasm32`? This seems reasonable to enable at the "standard library" level of whatever language you are targeting. In C/C++, this is done with macro definitions: e.g., `__wasm32__`. In which language or environment are you interested in these being available? It might be helpful to understand the context of what you're working on.

**Comment by vdshb** [comment]
Thank you for your answer. Initially I wanted to hide all Kotlin-related stuff as irrelevant, but you are right. Let me describe my context. I'm creating a set of kotlin multiplatform libraries (not published yet) and I'm thinking about supporting WASI target. 

Quick intro: kotlin multiplatform is a technology to compile kotlin into JVM, Native Linux, Native Win32, Native Mac, JS and WASM (Experimental WASI support was added last week) targets.

My libraries are architecture blocks which have the same API for end-user, but different implementations for different targets. Some of these libraries communicate with local file system on different targets or run child processes on different targets. 

In NodeJs `process.platform` contain OS type (like `linux` or `win32`). 

My most common use case of using it is determining what kind of path should I use when talking with file system. Windows like `C:\path\to\database` or UNIX-Like `/path/to/database`. 

Another simple to describe use case is to determine what external command to run to achieve the same goal on different OS. If I'm on `linux` or `darwin`. I typically have `ls`. On `win32` I typically have `cmd /c dir`. The same might be valid for different postgres configuring on different OS or using `OpenOffice Writer`/`MS Word` for some document processing. (I've made up the cases with postgres and office suits to show the possibilities. `ls`/`dir` commands I'm actually planning to use to automate some processes in multiplatform CI/CD pipelines).

 `process.arch`, on the other hand has really rare use cases. It's about distinguishing `arm64` from `x64`, etc. I use it only in build configs to determine what targets to compile on which environment. Kotlin-specific stuff. But my core library is detecting it in the most of supported platforms (except browsers), so I'm trying to support it as well in case anyone need it later.

**Comment by vdshb** [comment]
I suppose returning 42 for PID is just a joke. No PID - no API. That's fine. I've just started to realize what WASI is, so some of my thoughts might be naive. 

Correct me if I'm wrong, but as I see, WASI supports interaction with file system. I suppose both Windows like `C:\path\to\database` and UNIX-Like `/path/to/database` paths are acceptable on different platforms.
In this case getting OS type in runtime is nice to have to write the single code for both path-types.

I believe distinguishing `arm64` from `x64`, `arm32` or `risc-v` is also helpful in rare scenarios. Probably in scenarious when I want to write a bazel-like build tool or CI/CD tool on WASM. Please, let me know if I understand the purpose of WASI poorly and it will never target such use-cases.

**Comment by abrown** [comment]
(sorry for the delay... busy on other things!). I think the more you dive into Wasm/WASI the more you will see that they are actually trying to abstract away the kinds of differences you are talking about here. For paths, there are no drives or mounts visible, just  preopened directories that the host allows us to access. For OS tools, we might recompile the tool as a [component]; WASI won't allow us to call arbitrary system binaries outside the Wasm sandbox. For the target architecture, we only really can see the `wasm` target; under the hood, an engine may JIT-compile the Wasm to a native target, but we won't be able to inspect that.

[component]: https://github.com/WebAssembly/component-model

**Comment by pchickey** [comment]
> I believe distinguishing arm64 from x64, arm32 or risc-v is also helpful in rare scenarios. Probably in scenarious when I want to write a bazel-like build tool or CI/CD tool on WASM. Please, let me know if I understand the purpose of WASI poorly and it will never target such use-cases.

For those specialized use cases, you could use wit to write a nonstandard API to expose that information to your program, but in general WASI doesn't want to expose that sort of implementation detail about the host platform.

**Comment by vdshb** [comment]
Thanks for your answers, especially mentioning wasm-components. It all makes sense.

Feel free to close this issue if you think it's irrelevant or keep it open if having such use cases in mind might help to design better WASI  abstractions in the future.

**Comment by pchickey** [comment]
Thanks, we'll close it now and invite folks who have related questions to open a new issue with them.
