### ISSUE TITLE
Mismatch in return type for rust WASI APIs

### ISSUE THREAD

**Issue by zoraaver** [WebAssembly/WASI#569]
Going by the ABI defined [here](https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/headers/public/wasi/api.h#L108), it looks like WASI functions should return a 16-bit unsigned int. On the other hand, looking at the [generated rust bindings file](https://github.com/bytecodealliance/wasi/blob/main/src/lib_generated.rs#L2171-L2364), the return type appears to be a 32-bit signed int.

I ran into a hard-to-debug issue when testing some WASI functions on WAMR due to this mismatch. The WASI functions were panicking even though the return value from the native runtime function was `0`. Essentially what was happening is that the `uint16` value from native was being interpreted as an `int32` and the upper 16 bits contained garbage. Then, an error was raised since the value isn't cast back to a `uint16` till later on - e.g. see https://github.com/bytecodealliance/wasi/blob/main/src/lib_generated.rs#L1256-L1268. I only ran into this issue when compiling WAMR with clangcl on Windows but I think that just means other compilers may happen to conveniently zero out the upper 16-bits. 

example WASM app to demonstrate the issue:

```
use std::mem::MaybeUninit;

pub mod wasi_snapshot_preview1 {
    #[link(wasm_import_module = "wasi_snapshot_preview1")]
    extern "C" {
        /// Return environment variable data sizes.
        pub fn environ_sizes_get(arg0: i32, arg1: i32) -> i32;
    }
}

fn main() {
    let mut rp0 = MaybeUninit::<usize>::uninit();
    let mut rp1 = MaybeUninit::<usize>::uninit();
    let ret = unsafe {
        wasi_snapshot_preview1::environ_sizes_get(rp0.as_mut_ptr() as i32, rp1.as_mut_ptr() as i32)
    };

    println!("Ret is {}", ret);
}
```

which prints out garbage return values e.g. 2117795840 or 0x7E3B0000 in hex. But if I change the signature of `wasi_snapshot_preview1::environ_sizes_get` to return a `u16` , the return value is `0` as expected (assuming the function is correctly implemented by the runtime).

Is the `i32` return type in rust intentional? It would be great if we could amend it to match the ABI defined in C so that it's `u16` but I'm not sure if there's some other reason it was set to `i32` in the first place.

Any thoughts or suggestions would be appreciated, thanks.

**Comment by sbc100** [comment]
wasm itself doesn't have any integer types other than `i32` and `i64`.    There are no narrower types and no unsigned types.   This means that what C function that returns `uint16_t`, when compiled with wasm will have an `i32` return type.

So the return value from `environ_sizes_get` at the core wasm ABI level really is i32 (IIRC).  You can observe this if you disassembly an object file that references that C symbol.

I don't know how the rust stuff works but perhaps this information will be helpful?

**Comment by zoraaver** [comment]
Thanks for your quick response @sbc100! I've checked some other WASM language SDKs (AssemblyScript and wasi-libc) and they both seem to cast to uint16 before doing anything with the return value from a WASI function.

When I compiled with the return type set to `u16` for the aforementioned rust example, I noticed an extra function in the WAT file:
```
  (func (;196;) (type 4) (param i32 i32) (result i32)
    local.get 0
    i64.load16_u
    i32.const 1
    local.get 1
    call 235)
```
I assume the `i64.load16_u` is the important instruction here - it looks like even if the wasm ABI only specifies `i32` and `i64` for integers, there are [load instructions](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Memory/Load) to load narrower numbers from memory.

Therefore, I still feel that the return type should be changed to `u16` if that sounds reasonable. Also, I noticed previously the return type for these functions was `u16` but it seems to have been changed in this [commit](https://github.com/bytecodealliance/wasi/commit/d3c7a34193cb33d994b11104b22d234530232b5f) to `i32` and I'm not sure why (perhaps unintentionally?).

**Comment by sbc100** [comment]
> Thanks for your quick response @sbc100! I've checked some other WASM language SDKs (AssemblyScript and wasi-libc) and they both seem to cast to uint16 before doing anything with the return value from a WASI function.
> 
> When I compiled with the return type set to `u16` for the aforementioned rust example, I noticed an extra function in the WAT file:
> 
> ```
>   (func (;196;) (type 4) (param i32 i32) (result i32)
>     local.get 0
>     i64.load16_u
>     i32.const 1
>     local.get 1
>     call 235)
> ```
> 
> I assume the `i64.load16_u` is the important instruction here - it looks like even if the wasm ABI only specifies `i32` and `i64` for integers, there are [load instructions](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Memory/Load) to load narrower numbers from memory.
> 
> Therefore, I still feel that the return type should be changed to `u16` if that sounds reasonable. Also, I noticed previously the return type for these functions was `u16` but it seems to have been changed in this [commit](https://github.com/bytecodealliance/wasi/commit/d3c7a34193cb33d994b11104b22d234530232b5f) to `i32` and I'm not sure why (perhaps unintentionally?).

I'm not a rust person, but I imagine that one would want to use Wasm types when implementing Wasm functions.  And since Wasm itself does not have a `u16` type at all, maybe it doesn't make sense to use  a rust's `u16` type in the rust implementation of a Wasm function?   I'm outside my area of expertise though, so I'll shut up now and let @pchickey or @alexcrichton answer..

**Comment by zoraaver** [comment]
Thanks for your comprehensive answer. That all makes sense now. The issue indeed was fixed in WAMR by changing the host WASI functions to return a `uint32_t`. 

> Typically host<->guest interaction goes through some form of bindings generation to ensure errors like this do not happen.

We're missing that in WAMR so that's something we could add to avoid bugs like this in the future.
