### ISSUE TITLE
Proposal: WASI Observability API

### ISSUE THREAD

**Issue by chrisdickinson** [WebAssembly/WASI#573]
Hi folks! I've been working with my colleagues at Dylibso to port our `observe-sdk` bindings from core modules to the component model. We've started defining [an interface](https://github.com/dylibso/observe-sdk/blob/396ac45a02ea0ad867e861a1de347c3ae95981c2/wit/observe.wit) that captures the `observe-sdk`'s capabilities from a component perspective. The relevant WIT section [from that PR](https://github.com/dylibso/observe-sdk/pull/128) follows:

```wit
package dylibso:observe;

interface api {
  enum log-level {
    error,
    warn,
    info,
    debug,
    trace
  }

  enum metric-format {
    statsd,
  }

  metric: func(format: metric-format, name: list<u8>);
  log: func(level: log-level, msg: list<u8>);
  span-enter: func(name: string);
  span-tags: func(tags: string);
  span-exit: func();
}
```

We're interested in starting a conversation about what observability bindings look like at the WASI level. The `observe-sdk` takes the position of capturing high-level author intent (span creation, logging) while allowing the host to direct those intents to backing providers (via otel, datadog, honeycomb, zipkin, or lightstep.) We have the additional constraint that we'd like to continue to provide direct core module support for this interface, which others may or may not share.

We're interested in hearing what others think about this approach!

**Comment by oovm** [comment]
I have some disagreements with log-level, if you use enum to lock these levels, then other applications will have to force matching to these levels.

As far as I know, many frameworks and applications use six levels.

- For example, `log4j` uses `(FATAL, ERROR, WARN, INFO, DEBUG, TRACE)`,

- `Microsoft.Extensions.Logging` uses `(Critical, Error, Warning, Information, Debug, Trace)`

there are more

- [Syslog](https://www.rfc-editor.org/rfc/rfc5424#page-11) uses seven levels
- Apache Httpd uses ten levels

---

I'm not saying that enum should be expanded to more, what I'm saying is that for compatibility reasons, and to support various rural frameworks, log-level should be a number.

This number is ordered, and the user can choose to ignore all events less than a certain number.

**Comment by pchickey** [comment]
@oovm thanks for this feedback, the scope of this issue was to introduce `wasi-observe` which now has its own repository https://github.com/webassembly/wasi-observe, would you mind redirecting these comments to an issue there, or to https://github.com/webassembly/wasi-logging as appropriate?

**Comment by oovm** [comment]
@pchickey Can you move this issue to wasi-observe, I don't know who has permission to move issues in org?

---

My suggestion is to focus on wasi-observe, not wasi-logging.

The two are not quite the same, as proposed here https://github.com/WebAssembly/wasi-observe/issues/7.

I think a distinction should be made
