### ISSUE TITLE
Add launched Preview 2 WIT definitions to this repo

### ISSUE THREAD

**Issue by ricochet** [WebAssembly/WASI#576]
When we launch preview 2 world definitions, add the definitions to this repository as artifacts in the repo as well as as a release to make it easier to find and use the set of all WIT definitions used by WASI Preview 2.

Today the easiest tool to manage this is `wit-deps`. 

Proposal:
Create a `preview2/wit` directory and populate with all of the `0.2.0` WIT definitions.

**Comment by pchickey** [comment]
Agreed - lets make a draft PR with the current RCs in there to get everything staged

**Comment by ricochet** [comment]
We did this 🚀
