### ISSUE TITLE
 Proposal: WASI-WebGPU

### ISSUE THREAD

**Issue by MendyBerger** [WebAssembly/WASI#578]
Opening this to propose the addition of a webgpu spec I've been working on at https://github.com/MendyBerger/wasi-webgpu.

The explanation of the approach I'm taking, can be found in the readme.

The repo also includes other things like a mini-canvas and a frame-buffer. We might wanna consider those separately .

Please share any feedback you have.

**Comment by tareksander** [comment]
I can see that this proposal was on the agenda of [this meeting](https://github.com/WebAssembly/meetings/blob/main/wasi/2024/WASI-02-08.md), but there are currently no notes there. Has anything regarding this proposal been decided?

**Comment by MendyBerger** [comment]
Yes. We're now in phase 1. I'll be moving over the wit to https://github.com/WebAssembly/wasi-webgpu, and this will be the official repo going forward.

**Comment by pchickey** [comment]
Sorry that the notes were delayed, I forgot to put the PR up right away but it has now landed: https://github.com/WebAssembly/meetings/pull/1486

I'm going to close this issue, further discussion can take place on the https://github.com/WebAssembly/wasi-webgpu issues and the meetings scheduled by that group.
