### ISSUE TITLE
How to use sock in WASI?

### ISSUE THREAD

**Issue by bnmcxlzd** [WebAssembly/WASI#600]
How can I write a C program that uses a sock and compile it into Wasm binaries?
Are there any examples?

**Comment by ricochet** [comment]
Checkout the sockets test in wasmtime for a rust version of this: [crates/test-programs/src/sockets.rs](https://github.com/bytecodealliance/wasmtime/blob/4df1db571a3e136aecc864dcba65a6ed23f59d36/crates/test-programs/src/sockets.rs).

For C, you would use the [wasi-sdk](https://github.com/WebAssembly/wasi-sdk).
