### ISSUE TITLE
WebAssembly: A promising technology that is quietly being sabotaged

### ISSUE THREAD

**Issue by trcrsired** [WebAssembly/WASI#617]
https://kerkour.com/webassembly-wasi-preview2

That article is perfectly correct.
Many WASM vm developers including me we refuse to support this wasi p2 junk.

WASI P2 is literally Microsoft's failed UWP 2.0

**Comment by fitzgen** [comment]
Hi @trcrsired. What are your intentions with this post?

If you are trying to provide constructive criticism, and change the course of standards work, then I suggest you avoid the inflammatory language and focus on the technical feedback. People who have been pouring years of work into something are not going to respond well to their efforts being called "junk". I doubt you would either.

**Comment by devsnek** [comment]
I think there's a reasonable conversation to be had about how difficult it is to understand the component model (very difficult), but I don't think that this is the way to start that conversation, and given the content of the blog post I don't think the OP intends to have a reasonable conversation anyway.

**Comment by ricochet** [comment]
This issue is not presented in a constructive way and will not help move discussions forward. If you have specific addressable feedback, then those may be addressed in tractable issues. I am closing this as not productive.
