### ISSUE TITLE
Update `Proposals.md` document to reflect the current status of WASI proposals

### ISSUE THREAD

**Issue by diversable** [WebAssembly/WASI#631]
To keep the `Proposals.md` document in sync with the current state of WASI proposals, the "Clocks" and "CLI" propsals should be removed from the "Phase 2" list, since the proposals above are now in Phase 3; note that those same proposals are already listed under the "Phase 3" category, so they do not need to be moved, just removeed from Phase 2.

**Comment by pchickey** [comment]
Thanks!
