### ISSUE TITLE
Are inter-module interfaces outside the scope of WASI?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/WASI#68]
My current understanding is that this is outside the scope of WASI and that WASI is more like the system call layer, dedicated only to communicating with the embedder.    But I think there might be some level confusion (and I could be completely wrong). 

If my assumption is correct then I think it might be useful to list inter-module interfaces as explicitly outside the scope of WASI.  For example we might say that DLL-linkage schemes or "shared nothing" APIs don't make sense to be specified as WASI interfaces?

Note: this wouldn't prevent the capabilities model from functioning, since handles/capabilities received from WASI API calls could still be passed between modules.  It would just mean that the interfaces used *between* modules (e.g. in a DLL, or shared nothing shceme) is not something that would be specified as a WASI interface.

**Comment by wanderer** [comment]
At some point it might be nice to have an interface to create and interact with modules, such as getting funcRefs from the module's exports.

**Comment by sbc100** [comment]
> At some point it might be nice to have an interface to create and interact with modules, such as getting funcRefs from the module's exports.

Do you mean something along the lines of dlopen/dlsym for WASI?   That could make sense yes. Presumably that thing your would be interacting with there would not itself be specified as a WASI interface, but rather you would be using the dlopen WASI interface in order to fetch functions?

**Comment by wanderer** [comment]
> Presumably that thing your would be interacting with there would not itself be specified as a WASI interface, but rather you would be using the dlopen WASI interface in order to fetch functions?

yep that is what I was thinking

**Comment by sunfishcode** [comment]
I agree. For DLL linking schemes and "shared nothing" libraries, we should design these independently of WASI, in the [tool-conventions](https://github.com/WebAssembly/tool-conventions) repo and/or as part of [☃bindings](https://github.com/WebAssembly/webidl-bindings). There could be a WASI component to supporting something like `dlsym`, but we'd need to see how it would fit in the context of a library design.

**Comment by sbc100** [comment]
OK, in retrospect I think that the current wording in HighLevelGoals.md is probably clear enough: "...to serve as a system interface which can be used by WebAssembly code to interact with the outside world".

**Comment by brandonros** [comment]
> OK, in retrospect I think that the current wording in HighLevelGoals.md is probably clear enough: "...to serve as a system interface which can be used by WebAssembly code to interact with the outside world".

To be clear, does that mean WASI does *not* want to support the intermodule abstraction being discussed here? aka there are no intentions to support `dl_open` / `dl_sym` interfaces?

**Comment by sunfishcode** [comment]
We do want to support those interfaces; `dlopen` interacts with the outside world. It's just that WASI will only be one piece. We need to figure out what a library is, first. And there may even be multiple answers -- a C/C++ dynamic library concept, and a "shared nothing" library concept.

**Comment by brandonros** [comment]
I don't fully understand why this issue was closed then. Does it not make sense to implement `dl_open` and `dl_sym` inside the scope of WASI?

**Comment by sbc100** [comment]
Yes, to be clear I *am* in favor dl_sym/dl_open being on the table for bring part of a WASI API.

However the interface that a WASI app exports to another WASI app is not something that specified by a WASI API.  If I do `dl_sym(handle, "myfunc")` then perhaps dl_sym comes from a WASI API but the author of the app/dll that contains myfunc is not specifying a new WASI API.  

Another way of putting: When you create a new WASI app/dll using the WASI SDK you are *never* creating a new WASI API, you are creating something that uses the WASI APIs.  Its confusing because the things that the wasi-sks outputs are aften call WASI modules.  But that WASI API modules are something completely different.  I was just wanted to clarify that with this issue.

**Comment by brandonros** [comment]
> Another way of putting: When you create a new WASI app/dll using the WASI SDK you are never creating a new WASI API, you are creating something that uses the WASI APIs. 

I grasp that part. It's up to the runtime to implement `dl_sym` and `dl_open`.

Should I open a separate issue to get dl_sym + dl_open accepted as part of the WASI standard? It would obviously need to be coupled to some "you are giving up all safety rights" security privilege, but that's to be expected.
