### ISSUE TITLE
Make __wasi_linkcount_t 64-bit

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/WASI#70]
`__wasi_countcount_t` is currently a `uint32_t`. We should change it to `uint64_t` in order to support hypothetical filesystems with very large link counts. For comparison, the [nlink function in Rust](https://doc.rust-lang.org/std/os/unix/fs/trait.MetadataExt.html#tymethod.nlink) returns a 64-bit value.

This will increase the size of `__wasi_filestat_t`, however that seems negligible.

For comparison, the userspace `nlink_t` is already a `uint64_t`: https://github.com/rust-lang/libc/blob/master/src/wasi.rs#L34.

**Comment by jedisct1** [comment]
Good point. Yes, it would totally make sense to increase it to 64 bit.
