### ISSUE TITLE
Add a sleep function to the Core

### ISSUE THREAD

**Issue by newpavlov** [WebAssembly/WASI#77]
It seems like a pretty fundamental function, which is currently missing from the Core. It could be as simple as `sleep(uint64_t nanos)`.

**Comment by sunfishcode** [comment]
I'm the current API, the way to implement sleep is to use `poll_oneoff`, polling for a single `__WASI_EVENTTYPE_CLOCK` event.

**Comment by newpavlov** [comment]
Ah, good to know. :)
