### ISSUE TITLE
Add functions for manipulating enviromental variables to the Core API?

### ISSUE THREAD

**Issue by newpavlov** [WebAssembly/WASI#78]
We are able to retrieve environmental variables via `environ_get`, but there is no way to change them using Core. How about adding something like `setenv`/`unsetenv` (maybe merged into a single function)?

**Comment by sbc100** [comment]
IIRC the environment is all stored in linear memory (char **__environ in crt1.c), and setenv/unsetenv only effect the environment of the current process and its children, so there is no need for these to be syscalls.  They can be implemented purely in wasi-libc.

**Comment by sbc100** [comment]
Actually it looks like setenv/putenv/unsetenv are already compiled into wasi-libc .. so this should already work.
