### ISSUE TITLE
WASI is compatible with all Rust crates?

### ISSUE THREAD

**Issue by AchalaSB** [WebAssembly/WASI#80]
Hey, 
I'm planning to use WASI to compile my Rust code. But my question is if I use WASI, is it compatible to all rust crates?

Or is there any list to which and all crates WASI is supporting?

I think those crates which is having `wasm32-unknown-unknown` support will execute.

Thanks,
Achala

**Comment by devsnek** [comment]
not all rust crates, but probably most rust crates. it's more of a question of what rust's stdlib supports (with the exception of stuff like random).

**Comment by vitiral** [comment]
It is important to note that WASI is not yet standardized, so any final answer to this question is impossible until it is.

It is also important to note that certain crates are built specifically for certain platforms, i.e. posix or windows. While wasi aims to create a ["conceptual operating system"](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/) that attempts to be able to emulate most operating systems, it will certainly not support every possible syscall.

So to (maybe) answer your question: most rust crates that are pure logic should work -- which is probably most rust crates.

**Comment by leonwanghui** [comment]
Quite interesting topic. I am learning rust and wasm these days, and here are some conclusions from my side:

* Not support all crates. When I tried to compile some crates like `reqwest`, some errors occurred with bad network layer support.
* Currently for latest Rust (v1.37), there should be three targets supporting wasm which are `wasm32-unknown-unknown`, `wasm32-unknown-emscripten` and `wasm32-wasi`. So I think this could make users confused when choosing target to build the code.
* I found there are also many wasm compilers, so it's also confusing which one is better.

**Comment by AchalaSB** [comment]
Agree. All rust crates not supported. But most of crates having webassembly support i.e `wasm32-unknown-unknown` will support (have tested with 5-10 crates). 
`wasm32-unknown-unknown` and `wasm32-wasi` is almost similar. It is light-weight. `wasi` is having additional functionality as it is POSIX compliant. 
But another target with emscripten, it contains a JS glue code. if you wan't to use syscalls/Filesystems you may use that. And again the code is not optimized you may require external tools to optimize it like `wasm-gc`

**Comment by leonwanghui** [comment]
@AchalaSB If I get it right, if I want to try some system programming with wasi, the best option is `wasm32-wasi` target.

**Comment by AchalaSB** [comment]
@leonwanghui yes in that case try with wasi. 
But right now crates like `reqwest, hyper, web3, rpc` are not webassembly compatible. You may end up with some socket error etc.

**Comment by leonwanghui** [comment]
Found some issues on `hyper` and `reqwest` about wasm support: [https://github.com/hyperium/hyper/issues/1245](https://github.com/hyperium/hyper/issues/1245) [https://github.com/seanmonstar/reqwest/issues/288](https://github.com/seanmonstar/reqwest/issues/288)

**Comment by sunfishcode** [comment]
WASI doesn't currently have general networking support. We're aware this is an important feature and are working on it.
